/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Convox Gateway API
 * API for the Convox Gateway administration and proxy services.
 * OpenAPI spec version: 1.0
 */
import type {
  AuthLoginResponse,
  AuthLoginStartResponse,
  DbAPIToken,
  DbRackTLSCert,
  DbUser,
  GetAdminAuditExportParams,
  GetAdminAuditParams,
  GetAdminConfig200,
  GetAdminDeployRequestsParams,
  GetAdminRoles200,
  GetAdminSettings200,
  GetAuthCliCallbackParams,
  GetAuthWebCallbackParams,
  GetCreatedBy200,
  GetCreatedByParams,
  GetEnvParams,
  GetRack200,
  HandlersAuditLogsResponse,
  HandlersBackupCodesResponse,
  HandlersCLILoginCompleteRequest,
  HandlersConfirmTOTPEnrollmentRequest,
  HandlersCreateAPITokenRequest,
  HandlersCreateAPITokenResponse,
  HandlersCreateDeployRequestRequest,
  HandlersCreateUserRequest,
  HandlersCurrentUserResponse,
  HandlersDeployRequestList,
  HandlersDeployRequestResponse,
  HandlersEnvValuesResponse,
  HandlersHealthResponse,
  HandlersMFAStatusResponse,
  HandlersRevokeAllSessionsResponse,
  HandlersRevokeSessionResponse,
  HandlersStartTOTPEnrollmentResponse,
  HandlersStatusResponse,
  HandlersTokenPermissionMetadata,
  HandlersUpdateAPITokenRequest,
  HandlersUpdateAllowDestructiveActionsRequest,
  HandlersUpdateDeployRequestStatusRequest,
  HandlersUpdateEnvValuesRequest,
  HandlersUpdateEnvValuesResponse,
  HandlersUpdateMFASettingsRequest,
  HandlersUpdateProtectedEnvVarsRequest,
  HandlersUpdateUserProfileRequest,
  HandlersUpdateUserRolesRequest,
  HandlersUserSessionResponse,
  HandlersUserSummary,
  HandlersVerifyMFARequest,
  HandlersVerifyMFAResponse,
} from './schemas';

import { createGatewayClient } from './http-client';
type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getConvoxGatewayAPI = () => {
  /**
   * Returns paginated audit logs filtered by optional query parameters.
   * @summary List audit logs
   */
  const getAdminAudit = (
    params?: GetAdminAuditParams,
    options?: SecondParameter<typeof createGatewayClient>,
  ) => {
    return createGatewayClient<HandlersAuditLogsResponse>(
      { url: `/admin/audit`, method: 'GET', params },
      options,
    );
  };

  /**
   * Streams the filtered audit log dataset as CSV.
   * @summary Export audit logs as CSV
   */
  const getAdminAuditExport = (
    params?: GetAdminAuditExportParams,
    options?: SecondParameter<typeof createGatewayClient>,
  ) => {
    return createGatewayClient<Blob>(
      {
        url: `/admin/audit/export`,
        method: 'GET',
        params,
        responseType: 'blob',
      },
      options,
    );
  };

  /**
   * Returns the legacy user/domain configuration payload (deprecated).
   * @summary Get legacy configuration
   */
  const getAdminConfig = (
    options?: SecondParameter<typeof createGatewayClient>,
  ) => {
    return createGatewayClient<GetAdminConfig200>(
      { url: `/admin/config`, method: 'GET' },
      options,
    );
  };

  /**
   * Placeholder endpoint retained for backwards compatibility. Always returns 501.
   * @summary Update legacy configuration
   */
  const putAdminConfig = (
    options?: SecondParameter<typeof createGatewayClient>,
  ) => {
    return createGatewayClient<unknown>(
      { url: `/admin/config`, method: 'PUT' },
      options,
    );
  };

  /**
   * Lists deploy approval requests (admin).
   * @summary List deploy approvals
   */
  const getAdminDeployRequests = (
    params?: GetAdminDeployRequestsParams,
    options?: SecondParameter<typeof createGatewayClient>,
  ) => {
    return createGatewayClient<HandlersDeployRequestList>(
      { url: `/admin/deploy-requests`, method: 'GET', params },
      options,
    );
  };

  /**
   * Approves a pending deploy approval request.
   * @summary Approve deploy request
   */
  const postAdminDeployRequestsIdApprove = (
    id: number,
    handlersUpdateDeployRequestStatusRequest: HandlersUpdateDeployRequestStatusRequest,
    options?: SecondParameter<typeof createGatewayClient>,
  ) => {
    return createGatewayClient<HandlersDeployRequestResponse>(
      {
        url: `/admin/deploy-requests/${id}/approve`,
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        data: handlersUpdateDeployRequestStatusRequest,
      },
      options,
    );
  };

  /**
   * Rejects a pending deploy approval request.
   * @summary Reject deploy request
   */
  const postAdminDeployRequestsIdReject = (
    id: number,
    handlersUpdateDeployRequestStatusRequest: HandlersUpdateDeployRequestStatusRequest,
    options?: SecondParameter<typeof createGatewayClient>,
  ) => {
    return createGatewayClient<HandlersDeployRequestResponse>(
      {
        url: `/admin/deploy-requests/${id}/reject`,
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        data: handlersUpdateDeployRequestStatusRequest,
      },
      options,
    );
  };

  /**
   * Returns metadata and permissions for each gateway RBAC role.
   * @summary List RBAC roles
   */
  const getAdminRoles = (
    options?: SecondParameter<typeof createGatewayClient>,
  ) => {
    return createGatewayClient<GetAdminRoles200>(
      { url: `/admin/roles`, method: 'GET' },
      options,
    );
  };

  /**
   * Returns administrative settings including protected env vars and rack TLS state.
   * @summary Get gateway admin settings
   */
  const getAdminSettings = (
    options?: SecondParameter<typeof createGatewayClient>,
  ) => {
    return createGatewayClient<GetAdminSettings200>(
      { url: `/admin/settings`, method: 'GET' },
      options,
    );
  };

  /**
   * Enables or disables destructive actions such as rack resets.
   * @summary Toggle destructive action protections
   */
  const putAdminSettingsAllowDestructiveActions = (
    handlersUpdateAllowDestructiveActionsRequest: HandlersUpdateAllowDestructiveActionsRequest,
    options?: SecondParameter<typeof createGatewayClient>,
  ) => {
    return createGatewayClient<HandlersStatusResponse>(
      {
        url: `/admin/settings/allow_destructive_actions`,
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        data: handlersUpdateAllowDestructiveActionsRequest,
      },
      options,
    );
  };

  /**
   * Configures whether MFA is required for all users.
   * @summary Update MFA enforcement defaults
   */
  const putAdminSettingsMfa = (
    handlersUpdateMFASettingsRequest: HandlersUpdateMFASettingsRequest,
    options?: SecondParameter<typeof createGatewayClient>,
  ) => {
    return createGatewayClient<HandlersStatusResponse>(
      {
        url: `/admin/settings/mfa`,
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        data: handlersUpdateMFASettingsRequest,
      },
      options,
    );
  };

  /**
   * Replaces the list of protected environment variable keys.
   * @summary Update protected environment variables
   */
  const putAdminSettingsProtectedEnvVars = (
    handlersUpdateProtectedEnvVarsRequest: HandlersUpdateProtectedEnvVarsRequest,
    options?: SecondParameter<typeof createGatewayClient>,
  ) => {
    return createGatewayClient<HandlersStatusResponse>(
      {
        url: `/admin/settings/protected_env_vars`,
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        data: handlersUpdateProtectedEnvVarsRequest,
      },
      options,
    );
  };

  /**
   * Fetches and stores the latest TLS certificate for the configured Convox rack.
   * @summary Refresh rack TLS certificate
   */
  const postAdminSettingsRackTlsCertRefresh = (
    options?: SecondParameter<typeof createGatewayClient>,
  ) => {
    return createGatewayClient<DbRackTLSCert>(
      { url: `/admin/settings/rack_tls_cert/refresh`, method: 'POST' },
      options,
    );
  };

  /**
   * Returns all API tokens configured in the system.
   * @summary List API tokens
   */
  const getAdminTokens = (
    options?: SecondParameter<typeof createGatewayClient>,
  ) => {
    return createGatewayClient<DbAPIToken[]>(
      { url: `/admin/tokens`, method: 'GET' },
      options,
    );
  };

  /**
   * Generates a new API token for automation or CI/CD use.
   * @summary Create an API token
   */
  const postAdminTokens = (
    handlersCreateAPITokenRequest: HandlersCreateAPITokenRequest,
    options?: SecondParameter<typeof createGatewayClient>,
  ) => {
    return createGatewayClient<HandlersCreateAPITokenResponse>(
      {
        url: `/admin/tokens`,
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        data: handlersCreateAPITokenRequest,
      },
      options,
    );
  };

  /**
   * Returns the permission catalog and metadata used to build API token forms.
   * @summary Get token permission metadata
   */
  const getAdminTokensPermissions = (
    options?: SecondParameter<typeof createGatewayClient>,
  ) => {
    return createGatewayClient<HandlersTokenPermissionMetadata>(
      { url: `/admin/tokens/permissions`, method: 'GET' },
      options,
    );
  };

  /**
   * Returns metadata for a specific API token.
   * @summary Get API token
   */
  const getAdminTokensTokenID = (
    tokenID: number,
    options?: SecondParameter<typeof createGatewayClient>,
  ) => {
    return createGatewayClient<DbAPIToken>(
      { url: `/admin/tokens/${tokenID}`, method: 'GET' },
      options,
    );
  };

  /**
   * Updates token metadata such as name and permissions.
   * @summary Update an API token
   */
  const putAdminTokensTokenID = (
    tokenID: number,
    handlersUpdateAPITokenRequest: HandlersUpdateAPITokenRequest,
    options?: SecondParameter<typeof createGatewayClient>,
  ) => {
    return createGatewayClient<DbAPIToken>(
      {
        url: `/admin/tokens/${tokenID}`,
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        data: handlersUpdateAPITokenRequest,
      },
      options,
    );
  };

  /**
   * Permanently removes an API token.
   * @summary Delete an API token
   */
  const deleteAdminTokensTokenID = (
    tokenID: number,
    options?: SecondParameter<typeof createGatewayClient>,
  ) => {
    return createGatewayClient<string>(
      { url: `/admin/tokens/${tokenID}`, method: 'DELETE' },
      options,
    );
  };

  /**
   * Returns every user configured in the gateway along with role assignments.
   * @summary List all gateway users
   */
  const getAdminUsers = (
    options?: SecondParameter<typeof createGatewayClient>,
  ) => {
    return createGatewayClient<DbUser[]>(
      { url: `/admin/users`, method: 'GET' },
      options,
    );
  };

  /**
   * Creates a new gateway user with the provided roles.
   * @summary Create a user
   */
  const postAdminUsers = (
    handlersCreateUserRequest: HandlersCreateUserRequest,
    options?: SecondParameter<typeof createGatewayClient>,
  ) => {
    return createGatewayClient<HandlersUserSummary>(
      {
        url: `/admin/users`,
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        data: handlersCreateUserRequest,
      },
      options,
    );
  };

  /**
   * Returns details for a single gateway user.
   * @summary Get a user
   */
  const getAdminUsersEmail = (
    email: string,
    options?: SecondParameter<typeof createGatewayClient>,
  ) => {
    return createGatewayClient<DbUser>(
      { url: `/admin/users/${email}`, method: 'GET' },
      options,
    );
  };

  /**
   * Updates a user's display name and/or email.
   * @summary Update user profile
   */
  const putAdminUsersEmail = (
    email: string,
    handlersUpdateUserProfileRequest: HandlersUpdateUserProfileRequest,
    options?: SecondParameter<typeof createGatewayClient>,
  ) => {
    return createGatewayClient<HandlersUserSummary>(
      {
        url: `/admin/users/${email}`,
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        data: handlersUpdateUserProfileRequest,
      },
      options,
    );
  };

  /**
   * Removes a gateway user and revokes all sessions they own.
   * @summary Delete a user
   */
  const deleteAdminUsersEmail = (
    email: string,
    options?: SecondParameter<typeof createGatewayClient>,
  ) => {
    return createGatewayClient<string>(
      { url: `/admin/users/${email}`, method: 'DELETE' },
      options,
    );
  };

  /**
   * Replaces the role assignments for a user.
   * @summary Update user roles
   */
  const putAdminUsersEmailRoles = (
    email: string,
    handlersUpdateUserRolesRequest: HandlersUpdateUserRolesRequest,
    options?: SecondParameter<typeof createGatewayClient>,
  ) => {
    return createGatewayClient<HandlersUserSummary>(
      {
        url: `/admin/users/${email}/roles`,
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        data: handlersUpdateUserRolesRequest,
      },
      options,
    );
  };

  /**
   * Returns the active (non-revoked) web sessions for the specified user.
   * @summary List active sessions for a user
   */
  const getAdminUsersEmailSessions = (
    email: string,
    options?: SecondParameter<typeof createGatewayClient>,
  ) => {
    return createGatewayClient<HandlersUserSessionResponse[]>(
      { url: `/admin/users/${email}/sessions`, method: 'GET' },
      options,
    );
  };

  /**
   * Revokes every active session belonging to the specified user.
   * @summary Revoke all sessions for a user
   */
  const postAdminUsersEmailSessionsRevokeAll = (
    email: string,
    options?: SecondParameter<typeof createGatewayClient>,
  ) => {
    return createGatewayClient<HandlersRevokeAllSessionsResponse>(
      { url: `/admin/users/${email}/sessions/revoke_all`, method: 'POST' },
      options,
    );
  };

  /**
   * Revokes a single session for the specified user.
   * @summary Revoke a user session
   */
  const postAdminUsersEmailSessionsSessionIDRevoke = (
    email: string,
    sessionID: number,
    options?: SecondParameter<typeof createGatewayClient>,
  ) => {
    return createGatewayClient<HandlersRevokeSessionResponse>(
      {
        url: `/admin/users/${email}/sessions/${sessionID}/revoke`,
        method: 'POST',
      },
      options,
    );
  };

  /**
   * Stores the OAuth authorization code for the CLI to finish login.
   * @summary Complete CLI OAuth redirect
   */
  const getAuthCliCallback = (
    params: GetAuthCliCallbackParams,
    options?: SecondParameter<typeof createGatewayClient>,
  ) => {
    return createGatewayClient<unknown>(
      { url: `/auth/cli/callback`, method: 'GET', params },
      options,
    );
  };

  /**
   * Exchanges the stored authorization code and PKCE verifier for a session token.
   * @summary Finalize CLI OAuth login
   */
  const postAuthCliComplete = (
    handlersCLILoginCompleteRequest: HandlersCLILoginCompleteRequest,
    options?: SecondParameter<typeof createGatewayClient>,
  ) => {
    return createGatewayClient<AuthLoginResponse>(
      {
        url: `/auth/cli/complete`,
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        data: handlersCLILoginCompleteRequest,
      },
      options,
    );
  };

  /**
   * Initiates the CLI OAuth flow and returns PKCE parameters.
   * @summary Start CLI OAuth login
   */
  const postAuthCliStart = (
    options?: SecondParameter<typeof createGatewayClient>,
  ) => {
    return createGatewayClient<AuthLoginStartResponse>(
      { url: `/auth/cli/start`, method: 'POST' },
      options,
    );
  };

  /**
   * Generates a fresh set of backup codes. Existing codes are invalidated immediately.
   * @summary Regenerate backup codes
   */
  const postAuthMfaBackupCodesRegenerate = (
    options?: SecondParameter<typeof createGatewayClient>,
  ) => {
    return createGatewayClient<HandlersBackupCodesResponse>(
      { url: `/auth/mfa/backup-codes/regenerate`, method: 'POST' },
      options,
    );
  };

  /**
   * Confirms the TOTP secret using a verification code and optionally trusts the device.
   * @summary Confirm TOTP enrollment
   */
  const postAuthMfaEnrollTotpConfirm = (
    handlersConfirmTOTPEnrollmentRequest: HandlersConfirmTOTPEnrollmentRequest,
    options?: SecondParameter<typeof createGatewayClient>,
  ) => {
    return createGatewayClient<HandlersVerifyMFAResponse>(
      {
        url: `/auth/mfa/enroll/totp/confirm`,
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        data: handlersConfirmTOTPEnrollmentRequest,
      },
      options,
    );
  };

  /**
   * Generates a TOTP secret, provisioning URI, and backup codes for the authenticated user.
   * @summary Start TOTP enrollment
   */
  const postAuthMfaEnrollTotpStart = (
    options?: SecondParameter<typeof createGatewayClient>,
  ) => {
    return createGatewayClient<HandlersStartTOTPEnrollmentResponse>(
      { url: `/auth/mfa/enroll/totp/start`, method: 'POST' },
      options,
    );
  };

  /**
   * Removes an existing MFA method for the current user.
   * @summary Delete an MFA method
   */
  const deleteAuthMfaMethodsMethodID = (
    methodID: number,
    options?: SecondParameter<typeof createGatewayClient>,
  ) => {
    return createGatewayClient<HandlersStatusResponse>(
      { url: `/auth/mfa/methods/${methodID}`, method: 'DELETE' },
      options,
    );
  };

  /**
   * Returns enrollment state, configured methods, trusted devices, and backup code summary.
   * @summary Get MFA status for current session
   */
  const getAuthMfaStatus = (
    options?: SecondParameter<typeof createGatewayClient>,
  ) => {
    return createGatewayClient<HandlersMFAStatusResponse>(
      { url: `/auth/mfa/status`, method: 'GET' },
      options,
    );
  };

  /**
   * Revokes a trusted device token for the current user.
   * @summary Revoke a trusted device
   */
  const deleteAuthMfaTrustedDevicesDeviceID = (
    deviceID: number,
    options?: SecondParameter<typeof createGatewayClient>,
  ) => {
    return createGatewayClient<HandlersStatusResponse>(
      { url: `/auth/mfa/trusted-devices/${deviceID}`, method: 'DELETE' },
      options,
    );
  };

  /**
   * Verifies a TOTP or backup code to satisfy the MFA step-up requirement.
   * @summary Verify MFA step-up
   */
  const postAuthMfaVerify = (
    handlersVerifyMFARequest: HandlersVerifyMFARequest,
    options?: SecondParameter<typeof createGatewayClient>,
  ) => {
    return createGatewayClient<HandlersVerifyMFAResponse>(
      {
        url: `/auth/mfa/verify`,
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        data: handlersVerifyMFARequest,
      },
      options,
    );
  };

  /**
   * Validates the OAuth callback, issues a session cookie, and redirects to the SPA.
   * @summary Complete web OAuth login
   */
  const getAuthWebCallback = (
    params: GetAuthWebCallbackParams,
    options?: SecondParameter<typeof createGatewayClient>,
  ) => {
    return createGatewayClient<unknown>(
      { url: `/auth/web/callback`, method: 'GET', params },
      options,
    );
  };

  /**
   * Redirects the browser to the identity provider for login.
   * @summary Start web OAuth login
   */
  const getAuthWebLogin = (
    options?: SecondParameter<typeof createGatewayClient>,
  ) => {
    return createGatewayClient<unknown>(
      { url: `/auth/web/login`, method: 'GET' },
      options,
    );
  };

  /**
   * Revokes the active session, clears the cookie, and redirects to the login screen.
   * @summary Log out current session
   */
  const getAuthWebLogout = (
    options?: SecondParameter<typeof createGatewayClient>,
  ) => {
    return createGatewayClient<unknown>(
      { url: `/auth/web/logout`, method: 'GET' },
      options,
    );
  };

  /**
   * Returns creator information for the supplied resource identifiers.
   * @summary Get resource creator metadata
   */
  const getCreatedBy = (
    params: GetCreatedByParams,
    options?: SecondParameter<typeof createGatewayClient>,
  ) => {
    return createGatewayClient<GetCreatedBy200>(
      { url: `/created-by`, method: 'GET', params },
      options,
    );
  };

  /**
   * Creates a manual approval record tied to an API token.
   * @summary Request deploy approval
   */
  const postDeployRequests = (
    handlersCreateDeployRequestRequest: HandlersCreateDeployRequestRequest,
    options?: SecondParameter<typeof createGatewayClient>,
  ) => {
    return createGatewayClient<HandlersDeployRequestResponse>(
      {
        url: `/deploy-requests`,
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        data: handlersCreateDeployRequestRequest,
      },
      options,
    );
  };

  /**
   * Returns the status of a deploy approval request.
   * @summary Get deploy approval
   */
  const getDeployRequestsId = (
    id: number,
    options?: SecondParameter<typeof createGatewayClient>,
  ) => {
    return createGatewayClient<HandlersDeployRequestResponse>(
      { url: `/deploy-requests/${id}`, method: 'GET' },
      options,
    );
  };

  /**
   * Returns environment variables for a Convox app, masking secrets unless authorized.
   * @summary Get environment variables
   */
  const getEnv = (
    params: GetEnvParams,
    options?: SecondParameter<typeof createGatewayClient>,
  ) => {
    return createGatewayClient<HandlersEnvValuesResponse>(
      { url: `/env`, method: 'GET', params },
      options,
    );
  };

  /**
   * Applies environment variable changes for a Convox app by creating a new release. Secrets remain masked unless the user has secrets permissions.
   * @summary Update environment variables
   */
  const putEnv = (
    handlersUpdateEnvValuesRequest: HandlersUpdateEnvValuesRequest,
    options?: SecondParameter<typeof createGatewayClient>,
  ) => {
    return createGatewayClient<HandlersUpdateEnvValuesResponse>(
      {
        url: `/env`,
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        data: handlersUpdateEnvValuesRequest,
      },
      options,
    );
  };

  /**
   * Returns service health information.
   * @summary Health check
   */
  const getHealth = (options?: SecondParameter<typeof createGatewayClient>) => {
    return createGatewayClient<HandlersHealthResponse>(
      { url: `/health`, method: 'GET' },
      options,
    );
  };

  /**
   * Returns the authenticated user's profile, roles, and default rack summary.
   * @summary Get current user profile
   */
  const getMe = (options?: SecondParameter<typeof createGatewayClient>) => {
    return createGatewayClient<HandlersCurrentUserResponse>(
      { url: `/me`, method: 'GET' },
      options,
    );
  };

  /**
   * Proxies the rack /system endpoint returning the rack's metadata.
   * @summary Get rack system information
   */
  const getRack = (options?: SecondParameter<typeof createGatewayClient>) => {
    return createGatewayClient<GetRack200>(
      { url: `/rack`, method: 'GET' },
      options,
    );
  };

  return {
    getAdminAudit,
    getAdminAuditExport,
    getAdminConfig,
    putAdminConfig,
    getAdminDeployRequests,
    postAdminDeployRequestsIdApprove,
    postAdminDeployRequestsIdReject,
    getAdminRoles,
    getAdminSettings,
    putAdminSettingsAllowDestructiveActions,
    putAdminSettingsMfa,
    putAdminSettingsProtectedEnvVars,
    postAdminSettingsRackTlsCertRefresh,
    getAdminTokens,
    postAdminTokens,
    getAdminTokensPermissions,
    getAdminTokensTokenID,
    putAdminTokensTokenID,
    deleteAdminTokensTokenID,
    getAdminUsers,
    postAdminUsers,
    getAdminUsersEmail,
    putAdminUsersEmail,
    deleteAdminUsersEmail,
    putAdminUsersEmailRoles,
    getAdminUsersEmailSessions,
    postAdminUsersEmailSessionsRevokeAll,
    postAdminUsersEmailSessionsSessionIDRevoke,
    getAuthCliCallback,
    postAuthCliComplete,
    postAuthCliStart,
    postAuthMfaBackupCodesRegenerate,
    postAuthMfaEnrollTotpConfirm,
    postAuthMfaEnrollTotpStart,
    deleteAuthMfaMethodsMethodID,
    getAuthMfaStatus,
    deleteAuthMfaTrustedDevicesDeviceID,
    postAuthMfaVerify,
    getAuthWebCallback,
    getAuthWebLogin,
    getAuthWebLogout,
    getCreatedBy,
    postDeployRequests,
    getDeployRequestsId,
    getEnv,
    putEnv,
    getHealth,
    getMe,
    getRack,
  };
};
export type GetAdminAuditResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getConvoxGatewayAPI>['getAdminAudit']>>
>;
export type GetAdminAuditExportResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getConvoxGatewayAPI>['getAdminAuditExport']>
  >
>;
export type GetAdminConfigResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getConvoxGatewayAPI>['getAdminConfig']>>
>;
export type PutAdminConfigResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getConvoxGatewayAPI>['putAdminConfig']>>
>;
export type GetAdminDeployRequestsResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getConvoxGatewayAPI>['getAdminDeployRequests']>
  >
>;
export type PostAdminDeployRequestsIdApproveResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getConvoxGatewayAPI>['postAdminDeployRequestsIdApprove']
    >
  >
>;
export type PostAdminDeployRequestsIdRejectResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getConvoxGatewayAPI>['postAdminDeployRequestsIdReject']
    >
  >
>;
export type GetAdminRolesResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getConvoxGatewayAPI>['getAdminRoles']>>
>;
export type GetAdminSettingsResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getConvoxGatewayAPI>['getAdminSettings']>
  >
>;
export type PutAdminSettingsAllowDestructiveActionsResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getConvoxGatewayAPI
      >['putAdminSettingsAllowDestructiveActions']
    >
  >
>;
export type PutAdminSettingsMfaResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getConvoxGatewayAPI>['putAdminSettingsMfa']>
  >
>;
export type PutAdminSettingsProtectedEnvVarsResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getConvoxGatewayAPI>['putAdminSettingsProtectedEnvVars']
    >
  >
>;
export type PostAdminSettingsRackTlsCertRefreshResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getConvoxGatewayAPI
      >['postAdminSettingsRackTlsCertRefresh']
    >
  >
>;
export type GetAdminTokensResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getConvoxGatewayAPI>['getAdminTokens']>>
>;
export type PostAdminTokensResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getConvoxGatewayAPI>['postAdminTokens']>>
>;
export type GetAdminTokensPermissionsResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getConvoxGatewayAPI>['getAdminTokensPermissions']
    >
  >
>;
export type GetAdminTokensTokenIDResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getConvoxGatewayAPI>['getAdminTokensTokenID']>
  >
>;
export type PutAdminTokensTokenIDResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getConvoxGatewayAPI>['putAdminTokensTokenID']>
  >
>;
export type DeleteAdminTokensTokenIDResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getConvoxGatewayAPI>['deleteAdminTokensTokenID']
    >
  >
>;
export type GetAdminUsersResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getConvoxGatewayAPI>['getAdminUsers']>>
>;
export type PostAdminUsersResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getConvoxGatewayAPI>['postAdminUsers']>>
>;
export type GetAdminUsersEmailResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getConvoxGatewayAPI>['getAdminUsersEmail']>
  >
>;
export type PutAdminUsersEmailResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getConvoxGatewayAPI>['putAdminUsersEmail']>
  >
>;
export type DeleteAdminUsersEmailResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getConvoxGatewayAPI>['deleteAdminUsersEmail']>
  >
>;
export type PutAdminUsersEmailRolesResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getConvoxGatewayAPI>['putAdminUsersEmailRoles']
    >
  >
>;
export type GetAdminUsersEmailSessionsResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getConvoxGatewayAPI>['getAdminUsersEmailSessions']
    >
  >
>;
export type PostAdminUsersEmailSessionsRevokeAllResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getConvoxGatewayAPI
      >['postAdminUsersEmailSessionsRevokeAll']
    >
  >
>;
export type PostAdminUsersEmailSessionsSessionIDRevokeResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getConvoxGatewayAPI
      >['postAdminUsersEmailSessionsSessionIDRevoke']
    >
  >
>;
export type GetAuthCliCallbackResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getConvoxGatewayAPI>['getAuthCliCallback']>
  >
>;
export type PostAuthCliCompleteResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getConvoxGatewayAPI>['postAuthCliComplete']>
  >
>;
export type PostAuthCliStartResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getConvoxGatewayAPI>['postAuthCliStart']>
  >
>;
export type PostAuthMfaBackupCodesRegenerateResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getConvoxGatewayAPI>['postAuthMfaBackupCodesRegenerate']
    >
  >
>;
export type PostAuthMfaEnrollTotpConfirmResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getConvoxGatewayAPI>['postAuthMfaEnrollTotpConfirm']
    >
  >
>;
export type PostAuthMfaEnrollTotpStartResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getConvoxGatewayAPI>['postAuthMfaEnrollTotpStart']
    >
  >
>;
export type DeleteAuthMfaMethodsMethodIDResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getConvoxGatewayAPI>['deleteAuthMfaMethodsMethodID']
    >
  >
>;
export type GetAuthMfaStatusResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getConvoxGatewayAPI>['getAuthMfaStatus']>
  >
>;
export type DeleteAuthMfaTrustedDevicesDeviceIDResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getConvoxGatewayAPI
      >['deleteAuthMfaTrustedDevicesDeviceID']
    >
  >
>;
export type PostAuthMfaVerifyResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getConvoxGatewayAPI>['postAuthMfaVerify']>
  >
>;
export type GetAuthWebCallbackResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getConvoxGatewayAPI>['getAuthWebCallback']>
  >
>;
export type GetAuthWebLoginResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getConvoxGatewayAPI>['getAuthWebLogin']>>
>;
export type GetAuthWebLogoutResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getConvoxGatewayAPI>['getAuthWebLogout']>
  >
>;
export type GetCreatedByResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getConvoxGatewayAPI>['getCreatedBy']>>
>;
export type PostDeployRequestsResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getConvoxGatewayAPI>['postDeployRequests']>
  >
>;
export type GetDeployRequestsIdResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getConvoxGatewayAPI>['getDeployRequestsId']>
  >
>;
export type GetEnvResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getConvoxGatewayAPI>['getEnv']>>
>;
export type PutEnvResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getConvoxGatewayAPI>['putEnv']>>
>;
export type GetHealthResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getConvoxGatewayAPI>['getHealth']>>
>;
export type GetMeResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getConvoxGatewayAPI>['getMe']>>
>;
export type GetRackResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getConvoxGatewayAPI>['getRack']>>
>;
