/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Rack Gateway API
 * API for the Rack Gateway administration and proxy services.
 * OpenAPI spec version: 1.0
 */
import type {
  AuthLoginStartResponse,
  DbAPIToken,
  DbRackTLSCert,
  DbUser,
  DeleteAppsAppSettings200,
  DeleteAppsAppSettingsApprovedDeployCommands200,
  DeleteAppsAppSettingsParams,
  DeleteAppsAppSettingsProtectedEnvVars200,
  DeleteAppsAppSettingsSecretEnvVars200,
  DeleteAppsAppSettingsServiceImagePatterns200,
  DeleteSettings200,
  DeleteSettingsParams,
  GetAppsAppEnvParams,
  GetAppsAppSettings200,
  GetAuditLogsExportParams,
  GetAuditLogsParams,
  GetAuthCliCallbackParams,
  GetAuthWebCallbackParams,
  GetCreatedBy200,
  GetCreatedByParams,
  GetDeployApprovalRequestsIdAuditLogsParams,
  GetDeployApprovalRequestsParams,
  GetRack200,
  GetRoles200,
  GetSettings200,
  HandlersAuditLogsResponse,
  HandlersBackupCodesResponse,
  HandlersCLILoginCompleteRequest,
  HandlersCLILoginResponse,
  HandlersConfirmTOTPEnrollmentRequest,
  HandlersConfirmWebAuthnEnrollmentRequest,
  HandlersCreateAPITokenRequest,
  HandlersCreateAPITokenResponse,
  HandlersCreateDeployApprovalRequestRequest,
  HandlersCreateUserRequest,
  HandlersDeployApprovalRequestList,
  HandlersDeployApprovalRequestResponse,
  HandlersEnvValuesResponse,
  HandlersHealthResponse,
  HandlersInfoResponse,
  HandlersLockUserRequest,
  HandlersMFAStatusResponse,
  HandlersRevokeAllSessionsResponse,
  HandlersRevokeSessionResponse,
  HandlersStartTOTPEnrollmentResponse,
  HandlersStartWebAuthnEnrollmentResponse,
  HandlersStartYubiOTPEnrollmentRequest,
  HandlersStartYubiOTPEnrollmentResponse,
  HandlersStatusResponse,
  HandlersTokenPermissionMetadata,
  HandlersUpdateAPITokenRequest,
  HandlersUpdateDeployApprovalRequestStatusRequest,
  HandlersUpdateEnvValuesRequest,
  HandlersUpdateEnvValuesResponse,
  HandlersUpdateMFAMethodRequest,
  HandlersUpdatePreferredMFAMethodRequest,
  HandlersUpdateUserNameRequest,
  HandlersUpdateUserRequest,
  HandlersUserSessionResponse,
  HandlersUserSummary,
  HandlersVerifyMFARequest,
  HandlersVerifyMFAResponse,
  HandlersVerifyWebAuthnAssertionRequest,
  HandlersWebAuthnAssertionStartResponse,
  HandlersWebAuthnEnrollmentResponse,
  PutAppsAppSettings200,
  PutAppsAppSettingsApprovedDeployCommands200,
  PutAppsAppSettingsProtectedEnvVars200,
  PutAppsAppSettingsSecretEnvVars200,
  PutAppsAppSettingsServiceImagePatterns200,
  PutAppsAppSettingsServiceImagePatternsBody,
  PutSettings200,
  SettingsBody,
  SettingsSetting,
} from './schemas';

import { createGatewayClient } from './http-client';
type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getRackGatewayAPI = () => {
  /**
   * Returns all API tokens configured in the system.
   * @summary List API tokens
   */
  const getApiTokens = (
    options?: SecondParameter<typeof createGatewayClient<DbAPIToken[]>>,
  ) => {
    return createGatewayClient<DbAPIToken[]>(
      { url: `/api-tokens`, method: 'GET' },
      options,
    );
  };

  /**
   * Generates a new API token for automation or CI/CD use.
   * @summary Create an API token
   */
  const postApiTokens = (
    handlersCreateAPITokenRequest: HandlersCreateAPITokenRequest,
    options?: SecondParameter<
      typeof createGatewayClient<HandlersCreateAPITokenResponse>
    >,
  ) => {
    return createGatewayClient<HandlersCreateAPITokenResponse>(
      {
        url: `/api-tokens`,
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        data: handlersCreateAPITokenRequest,
      },
      options,
    );
  };

  /**
   * Returns the permission catalog and metadata used to build API token forms.
   * @summary Get token permission metadata
   */
  const getApiTokensPermissions = (
    options?: SecondParameter<
      typeof createGatewayClient<HandlersTokenPermissionMetadata>
    >,
  ) => {
    return createGatewayClient<HandlersTokenPermissionMetadata>(
      { url: `/api-tokens/permissions`, method: 'GET' },
      options,
    );
  };

  /**
   * Returns metadata for a specific API token.
   * @summary Get API token
   */
  const getApiTokensTokenID = (
    tokenID: string,
    options?: SecondParameter<typeof createGatewayClient<DbAPIToken>>,
  ) => {
    return createGatewayClient<DbAPIToken>(
      { url: `/api-tokens/${tokenID}`, method: 'GET' },
      options,
    );
  };

  /**
   * Updates token metadata such as name and permissions.
   * @summary Update an API token
   */
  const putApiTokensTokenID = (
    tokenID: string,
    handlersUpdateAPITokenRequest: HandlersUpdateAPITokenRequest,
    options?: SecondParameter<typeof createGatewayClient<DbAPIToken>>,
  ) => {
    return createGatewayClient<DbAPIToken>(
      {
        url: `/api-tokens/${tokenID}`,
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        data: handlersUpdateAPITokenRequest,
      },
      options,
    );
  };

  /**
   * Permanently removes an API token.
   * @summary Delete an API token
   */
  const deleteApiTokensTokenID = (
    tokenID: string,
    options?: SecondParameter<typeof createGatewayClient<string>>,
  ) => {
    return createGatewayClient<string>(
      { url: `/api-tokens/${tokenID}`, method: 'DELETE' },
      options,
    );
  };

  /**
   * Returns environment variables for a Convox app, masking secrets unless authorized.
   * @summary Get environment variables
   */
  const getAppsAppEnv = (
    app: string,
    params?: GetAppsAppEnvParams,
    options?: SecondParameter<
      typeof createGatewayClient<HandlersEnvValuesResponse>
    >,
  ) => {
    return createGatewayClient<HandlersEnvValuesResponse>(
      { url: `/apps/${app}/env`, method: 'GET', params },
      options,
    );
  };

  /**
   * Applies environment variable changes for a Convox app by creating a new release. Secrets remain masked unless the user has secrets permissions.
   * @summary Update environment variables
   */
  const putAppsAppEnv = (
    app: string,
    handlersUpdateEnvValuesRequest: HandlersUpdateEnvValuesRequest,
    options?: SecondParameter<
      typeof createGatewayClient<HandlersUpdateEnvValuesResponse>
    >,
  ) => {
    return createGatewayClient<HandlersUpdateEnvValuesResponse>(
      {
        url: `/apps/${app}/env`,
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        data: handlersUpdateEnvValuesRequest,
      },
      options,
    );
  };

  /**
   * Returns all settings for a specific app with their sources
   * @summary Get all app settings
   */
  const getAppsAppSettings = (
    app: string,
    options?: SecondParameter<
      typeof createGatewayClient<GetAppsAppSettings200>
    >,
  ) => {
    return createGatewayClient<GetAppsAppSettings200>(
      { url: `/apps/${app}/settings`, method: 'GET' },
      options,
    );
  };

  /**
   * Updates multiple app settings atomically and stores them in the database
   * @summary Update multiple app settings
   */
  const putAppsAppSettings = (
    app: string,
    settingsBody: SettingsBody,
    options?: SecondParameter<
      typeof createGatewayClient<PutAppsAppSettings200>
    >,
  ) => {
    return createGatewayClient<PutAppsAppSettings200>(
      {
        url: `/apps/${app}/settings`,
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        data: settingsBody,
      },
      options,
    );
  };

  /**
   * Deletes multiple app settings from the database, reverting to env or default values
   * @summary Delete multiple app settings
   */
  const deleteAppsAppSettings = (
    app: string,
    params: DeleteAppsAppSettingsParams,
    options?: SecondParameter<
      typeof createGatewayClient<DeleteAppsAppSettings200>
    >,
  ) => {
    return createGatewayClient<DeleteAppsAppSettings200>(
      { url: `/apps/${app}/settings`, method: 'DELETE', params },
      options,
    );
  };

  /**
   * Replaces the approved deploy commands for the specified app
   * @summary Update approved deploy commands
   */
  const putAppsAppSettingsApprovedDeployCommands = (
    app: string,
    putAppsAppSettingsApprovedDeployCommandsBody: string[],
    options?: SecondParameter<
      typeof createGatewayClient<PutAppsAppSettingsApprovedDeployCommands200>
    >,
  ) => {
    return createGatewayClient<PutAppsAppSettingsApprovedDeployCommands200>(
      {
        url: `/apps/${app}/settings/approved-deploy-commands`,
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        data: putAppsAppSettingsApprovedDeployCommandsBody,
      },
      options,
    );
  };

  /**
   * Removes approved deploy command overrides for the specified app
   * @summary Delete approved deploy commands
   */
  const deleteAppsAppSettingsApprovedDeployCommands = (
    app: string,
    options?: SecondParameter<
      typeof createGatewayClient<DeleteAppsAppSettingsApprovedDeployCommands200>
    >,
  ) => {
    return createGatewayClient<DeleteAppsAppSettingsApprovedDeployCommands200>(
      {
        url: `/apps/${app}/settings/approved-deploy-commands`,
        method: 'DELETE',
      },
      options,
    );
  };

  /**
   * Replaces the list of protected environment variables for the specified app
   * @summary Update protected environment variables
   */
  const putAppsAppSettingsProtectedEnvVars = (
    app: string,
    putAppsAppSettingsProtectedEnvVarsBody: string[],
    options?: SecondParameter<
      typeof createGatewayClient<PutAppsAppSettingsProtectedEnvVars200>
    >,
  ) => {
    return createGatewayClient<PutAppsAppSettingsProtectedEnvVars200>(
      {
        url: `/apps/${app}/settings/protected-env-vars`,
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        data: putAppsAppSettingsProtectedEnvVarsBody,
      },
      options,
    );
  };

  /**
   * Removes protected environment variable overrides for the specified app
   * @summary Delete protected environment variables
   */
  const deleteAppsAppSettingsProtectedEnvVars = (
    app: string,
    options?: SecondParameter<
      typeof createGatewayClient<DeleteAppsAppSettingsProtectedEnvVars200>
    >,
  ) => {
    return createGatewayClient<DeleteAppsAppSettingsProtectedEnvVars200>(
      { url: `/apps/${app}/settings/protected-env-vars`, method: 'DELETE' },
      options,
    );
  };

  /**
   * Replaces the list of secret environment variables for the specified app
   * @summary Update secret environment variables
   */
  const putAppsAppSettingsSecretEnvVars = (
    app: string,
    putAppsAppSettingsSecretEnvVarsBody: string[],
    options?: SecondParameter<
      typeof createGatewayClient<PutAppsAppSettingsSecretEnvVars200>
    >,
  ) => {
    return createGatewayClient<PutAppsAppSettingsSecretEnvVars200>(
      {
        url: `/apps/${app}/settings/secret-env-vars`,
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        data: putAppsAppSettingsSecretEnvVarsBody,
      },
      options,
    );
  };

  /**
   * Removes secret environment variable overrides for the specified app
   * @summary Delete secret environment variables
   */
  const deleteAppsAppSettingsSecretEnvVars = (
    app: string,
    options?: SecondParameter<
      typeof createGatewayClient<DeleteAppsAppSettingsSecretEnvVars200>
    >,
  ) => {
    return createGatewayClient<DeleteAppsAppSettingsSecretEnvVars200>(
      { url: `/apps/${app}/settings/secret-env-vars`, method: 'DELETE' },
      options,
    );
  };

  /**
   * Replaces service image constraints for the specified app
   * @summary Update service image patterns
   */
  const putAppsAppSettingsServiceImagePatterns = (
    app: string,
    putAppsAppSettingsServiceImagePatternsBody: PutAppsAppSettingsServiceImagePatternsBody,
    options?: SecondParameter<
      typeof createGatewayClient<PutAppsAppSettingsServiceImagePatterns200>
    >,
  ) => {
    return createGatewayClient<PutAppsAppSettingsServiceImagePatterns200>(
      {
        url: `/apps/${app}/settings/service-image-patterns`,
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        data: putAppsAppSettingsServiceImagePatternsBody,
      },
      options,
    );
  };

  /**
   * Removes service image pattern overrides for the specified app
   * @summary Delete service image patterns
   */
  const deleteAppsAppSettingsServiceImagePatterns = (
    app: string,
    options?: SecondParameter<
      typeof createGatewayClient<DeleteAppsAppSettingsServiceImagePatterns200>
    >,
  ) => {
    return createGatewayClient<DeleteAppsAppSettingsServiceImagePatterns200>(
      { url: `/apps/${app}/settings/service-image-patterns`, method: 'DELETE' },
      options,
    );
  };

  /**
   * Returns paginated audit logs filtered by optional query parameters.
   * @summary List audit logs
   */
  const getAuditLogs = (
    params?: GetAuditLogsParams,
    options?: SecondParameter<
      typeof createGatewayClient<HandlersAuditLogsResponse>
    >,
  ) => {
    return createGatewayClient<HandlersAuditLogsResponse>(
      { url: `/audit-logs`, method: 'GET', params },
      options,
    );
  };

  /**
   * Streams the filtered audit log dataset as CSV.
   * @summary Export audit logs as CSV
   */
  const getAuditLogsExport = (
    params?: GetAuditLogsExportParams,
    options?: SecondParameter<typeof createGatewayClient<Blob>>,
  ) => {
    return createGatewayClient<Blob>(
      {
        url: `/audit-logs/export`,
        method: 'GET',
        params,
        responseType: 'blob',
      },
      options,
    );
  };

  /**
   * Stores the OAuth authorization code for the CLI to finish login.
   * @summary Complete CLI OAuth redirect
   */
  const getAuthCliCallback = (
    params: GetAuthCliCallbackParams,
    options?: SecondParameter<typeof createGatewayClient<unknown>>,
  ) => {
    return createGatewayClient<unknown>(
      { url: `/auth/cli/callback`, method: 'GET', params },
      options,
    );
  };

  /**
   * Exchanges the stored authorization code and PKCE verifier for a session token.
   * @summary Finalize CLI OAuth login
   */
  const postAuthCliComplete = (
    handlersCLILoginCompleteRequest: HandlersCLILoginCompleteRequest,
    options?: SecondParameter<
      typeof createGatewayClient<HandlersCLILoginResponse>
    >,
  ) => {
    return createGatewayClient<HandlersCLILoginResponse>(
      {
        url: `/auth/cli/complete`,
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        data: handlersCLILoginCompleteRequest,
      },
      options,
    );
  };

  /**
   * Initiates the CLI OAuth flow and returns PKCE parameters.
   * @summary Start CLI OAuth login
   */
  const postAuthCliStart = (
    options?: SecondParameter<
      typeof createGatewayClient<AuthLoginStartResponse>
    >,
  ) => {
    return createGatewayClient<AuthLoginStartResponse>(
      { url: `/auth/cli/start`, method: 'POST' },
      options,
    );
  };

  /**
   * Generates a new set of MFA backup codes. All prior codes become invalid.
   * @summary Regenerate backup codes
   */
  const postAuthMfaBackupCodesRegenerate = (
    options?: SecondParameter<
      typeof createGatewayClient<HandlersBackupCodesResponse>
    >,
  ) => {
    return createGatewayClient<HandlersBackupCodesResponse>(
      { url: `/auth/mfa/backup-codes/regenerate`, method: 'POST' },
      options,
    );
  };

  /**
   * Confirms the TOTP secret using a verification code and optionally trusts the device.
   * @summary Confirm TOTP enrollment
   */
  const postAuthMfaEnrollTotpConfirm = (
    handlersConfirmTOTPEnrollmentRequest: HandlersConfirmTOTPEnrollmentRequest,
    options?: SecondParameter<
      typeof createGatewayClient<HandlersVerifyMFAResponse>
    >,
  ) => {
    return createGatewayClient<HandlersVerifyMFAResponse>(
      {
        url: `/auth/mfa/enroll/totp/confirm`,
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        data: handlersConfirmTOTPEnrollmentRequest,
      },
      options,
    );
  };

  /**
   * Generates a TOTP secret, provisioning URI, and backup codes for the authenticated user.
   * @summary Start TOTP enrollment
   */
  const postAuthMfaEnrollTotpStart = (
    options?: SecondParameter<
      typeof createGatewayClient<HandlersStartTOTPEnrollmentResponse>
    >,
  ) => {
    return createGatewayClient<HandlersStartTOTPEnrollmentResponse>(
      { url: `/auth/mfa/enroll/totp/start`, method: 'POST' },
      options,
    );
  };

  /**
   * Completes WebAuthn credential registration with the client's credential response.
   * @summary Confirm WebAuthn enrollment
   */
  const postAuthMfaEnrollWebauthnConfirm = (
    handlersConfirmWebAuthnEnrollmentRequest: HandlersConfirmWebAuthnEnrollmentRequest,
    options?: SecondParameter<
      typeof createGatewayClient<HandlersWebAuthnEnrollmentResponse>
    >,
  ) => {
    return createGatewayClient<HandlersWebAuthnEnrollmentResponse>(
      {
        url: `/auth/mfa/enroll/webauthn/confirm`,
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        data: handlersConfirmWebAuthnEnrollmentRequest,
      },
      options,
    );
  };

  /**
   * Begins WebAuthn credential registration. Returns a challenge for the browser.
   * @summary Start WebAuthn enrollment
   */
  const postAuthMfaEnrollWebauthnStart = (
    options?: SecondParameter<
      typeof createGatewayClient<HandlersStartWebAuthnEnrollmentResponse>
    >,
  ) => {
    return createGatewayClient<HandlersStartWebAuthnEnrollmentResponse>(
      { url: `/auth/mfa/enroll/webauthn/start`, method: 'POST' },
      options,
    );
  };

  /**
   * Enrolls a Yubikey using Yubico OTP. Touch your Yubikey to generate an OTP.
   * @summary Start Yubico OTP enrollment
   */
  const postAuthMfaEnrollYubiotpStart = (
    handlersStartYubiOTPEnrollmentRequest: HandlersStartYubiOTPEnrollmentRequest,
    options?: SecondParameter<
      typeof createGatewayClient<HandlersStartYubiOTPEnrollmentResponse>
    >,
  ) => {
    return createGatewayClient<HandlersStartYubiOTPEnrollmentResponse>(
      {
        url: `/auth/mfa/enroll/yubiotp/start`,
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        data: handlersStartYubiOTPEnrollmentRequest,
      },
      options,
    );
  };

  /**
   * Updates the label of an MFA method
   * @summary Update MFA method label
   */
  const putAuthMfaMethodsMethodID = (
    methodID: number,
    handlersUpdateMFAMethodRequest: HandlersUpdateMFAMethodRequest,
    options?: SecondParameter<
      typeof createGatewayClient<HandlersStatusResponse>
    >,
  ) => {
    return createGatewayClient<HandlersStatusResponse>(
      {
        url: `/auth/mfa/methods/${methodID}`,
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        data: handlersUpdateMFAMethodRequest,
      },
      options,
    );
  };

  /**
   * Removes an existing MFA method for the current user.
   * @summary Delete an MFA method
   */
  const deleteAuthMfaMethodsMethodID = (
    methodID: number,
    options?: SecondParameter<
      typeof createGatewayClient<HandlersStatusResponse>
    >,
  ) => {
    return createGatewayClient<HandlersStatusResponse>(
      { url: `/auth/mfa/methods/${methodID}`, method: 'DELETE' },
      options,
    );
  };

  /**
   * Sets the user's preferred MFA method for sign-in (totp or webauthn)
   * @summary Update preferred MFA method
   */
  const putAuthMfaPreferredMethod = (
    handlersUpdatePreferredMFAMethodRequest: HandlersUpdatePreferredMFAMethodRequest,
    options?: SecondParameter<
      typeof createGatewayClient<HandlersStatusResponse>
    >,
  ) => {
    return createGatewayClient<HandlersStatusResponse>(
      {
        url: `/auth/mfa/preferred-method`,
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        data: handlersUpdatePreferredMFAMethodRequest,
      },
      options,
    );
  };

  /**
   * Returns enrollment state, configured methods, trusted devices, and backup code summary.
   * @summary Get MFA status for current session
   */
  const getAuthMfaStatus = (
    options?: SecondParameter<
      typeof createGatewayClient<HandlersMFAStatusResponse>
    >,
  ) => {
    return createGatewayClient<HandlersMFAStatusResponse>(
      { url: `/auth/mfa/status`, method: 'GET' },
      options,
    );
  };

  /**
   * Marks the current browser session as trusted by minting a trusted device cookie.
   * @summary Trust the current device
   */
  const postAuthMfaTrustedDevicesTrust = (
    options?: SecondParameter<
      typeof createGatewayClient<HandlersVerifyMFAResponse>
    >,
  ) => {
    return createGatewayClient<HandlersVerifyMFAResponse>(
      { url: `/auth/mfa/trusted-devices/trust`, method: 'POST' },
      options,
    );
  };

  /**
   * Revokes a trusted device, requiring MFA on next login from that device.
   * @summary Revoke a trusted device
   */
  const deleteAuthMfaTrustedDevicesDeviceID = (
    deviceID: number,
    options?: SecondParameter<
      typeof createGatewayClient<HandlersStatusResponse>
    >,
  ) => {
    return createGatewayClient<HandlersStatusResponse>(
      { url: `/auth/mfa/trusted-devices/${deviceID}`, method: 'DELETE' },
      options,
    );
  };

  /**
   * Verifies a TOTP or backup code to satisfy the MFA step-up requirement.
   * @summary Verify MFA step-up
   */
  const postAuthMfaVerify = (
    handlersVerifyMFARequest: HandlersVerifyMFARequest,
    options?: SecondParameter<
      typeof createGatewayClient<HandlersVerifyMFAResponse>
    >,
  ) => {
    return createGatewayClient<HandlersVerifyMFAResponse>(
      {
        url: `/auth/mfa/verify`,
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        data: handlersVerifyMFARequest,
      },
      options,
    );
  };

  /**
   * Begins a WebAuthn assertion ceremony for CLI login/step-up. Returns challenge and session data.
   * @summary Start WebAuthn assertion for MFA
   */
  const postAuthMfaWebauthnAssertionStart = (
    options?: SecondParameter<
      typeof createGatewayClient<HandlersWebAuthnAssertionStartResponse>
    >,
  ) => {
    return createGatewayClient<HandlersWebAuthnAssertionStartResponse>(
      { url: `/auth/mfa/webauthn/assertion/start`, method: 'POST' },
      options,
    );
  };

  /**
   * Completes the WebAuthn assertion ceremony by validating the signed response.
   * @summary Verify WebAuthn assertion for MFA
   */
  const postAuthMfaWebauthnAssertionVerify = (
    handlersVerifyWebAuthnAssertionRequest: HandlersVerifyWebAuthnAssertionRequest,
    options?: SecondParameter<
      typeof createGatewayClient<HandlersVerifyMFAResponse>
    >,
  ) => {
    return createGatewayClient<HandlersVerifyMFAResponse>(
      {
        url: `/auth/mfa/webauthn/assertion/verify`,
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        data: handlersVerifyWebAuthnAssertionRequest,
      },
      options,
    );
  };

  /**
   * Validates the OAuth callback, issues a session cookie, and redirects to the SPA.
   * @summary Complete web OAuth login
   */
  const getAuthWebCallback = (
    params: GetAuthWebCallbackParams,
    options?: SecondParameter<typeof createGatewayClient<unknown>>,
  ) => {
    return createGatewayClient<unknown>(
      { url: `/auth/web/callback`, method: 'GET', params },
      options,
    );
  };

  /**
   * Redirects the browser to the identity provider for login.
   * @summary Start web OAuth login
   */
  const getAuthWebLogin = (
    options?: SecondParameter<typeof createGatewayClient<unknown>>,
  ) => {
    return createGatewayClient<unknown>(
      { url: `/auth/web/login`, method: 'GET' },
      options,
    );
  };

  /**
   * Revokes the active session, clears the cookie, and redirects to the login screen.
   * @summary Log out current session
   */
  const getAuthWebLogout = (
    options?: SecondParameter<typeof createGatewayClient<unknown>>,
  ) => {
    return createGatewayClient<unknown>(
      { url: `/auth/web/logout`, method: 'GET' },
      options,
    );
  };

  /**
   * Returns creator information for the supplied resource identifiers.
   * @summary Get resource creator metadata
   */
  const getCreatedBy = (
    params: GetCreatedByParams,
    options?: SecondParameter<typeof createGatewayClient<GetCreatedBy200>>,
  ) => {
    return createGatewayClient<GetCreatedBy200>(
      { url: `/created-by`, method: 'GET', params },
      options,
    );
  };

  /**
   * Lists deploy approval requests (admin).
   * @summary List deploy approvals
   */
  const getDeployApprovalRequests = (
    params?: GetDeployApprovalRequestsParams,
    options?: SecondParameter<
      typeof createGatewayClient<HandlersDeployApprovalRequestList>
    >,
  ) => {
    return createGatewayClient<HandlersDeployApprovalRequestList>(
      { url: `/deploy-approval-requests`, method: 'GET', params },
      options,
    );
  };

  /**
   * Creates a manual approval record tied to an API token.
   * @summary Request deploy approval
   */
  const postDeployApprovalRequests = (
    handlersCreateDeployApprovalRequestRequest: HandlersCreateDeployApprovalRequestRequest,
    options?: SecondParameter<
      typeof createGatewayClient<HandlersDeployApprovalRequestResponse>
    >,
  ) => {
    return createGatewayClient<HandlersDeployApprovalRequestResponse>(
      {
        url: `/deploy-approval-requests`,
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        data: handlersCreateDeployApprovalRequestRequest,
      },
      options,
    );
  };

  /**
   * Returns the status of a deploy approval request.
   * @summary Get deploy approval
   */
  const getDeployApprovalRequestsId = (
    id: string,
    options?: SecondParameter<
      typeof createGatewayClient<HandlersDeployApprovalRequestResponse>
    >,
  ) => {
    return createGatewayClient<HandlersDeployApprovalRequestResponse>(
      { url: `/deploy-approval-requests/${id}`, method: 'GET' },
      options,
    );
  };

  /**
   * Approves a pending deploy approval request.
   * @summary Approve deploy approval request
   */
  const postDeployApprovalRequestsIdApprove = (
    id: string,
    handlersUpdateDeployApprovalRequestStatusRequest: HandlersUpdateDeployApprovalRequestStatusRequest,
    options?: SecondParameter<
      typeof createGatewayClient<HandlersDeployApprovalRequestResponse>
    >,
  ) => {
    return createGatewayClient<HandlersDeployApprovalRequestResponse>(
      {
        url: `/deploy-approval-requests/${id}/approve`,
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        data: handlersUpdateDeployApprovalRequestStatusRequest,
      },
      options,
    );
  };

  /**
   * Returns audit logs associated with a specific deploy approval request.
   * @summary Get audit logs for deploy approval request
   */
  const getDeployApprovalRequestsIdAuditLogs = (
    id: string,
    params?: GetDeployApprovalRequestsIdAuditLogsParams,
    options?: SecondParameter<
      typeof createGatewayClient<HandlersAuditLogsResponse>
    >,
  ) => {
    return createGatewayClient<HandlersAuditLogsResponse>(
      {
        url: `/deploy-approval-requests/${id}/audit-logs`,
        method: 'GET',
        params,
      },
      options,
    );
  };

  /**
   * Rejects a pending deploy approval request.
   * @summary Reject deploy approval request
   */
  const postDeployApprovalRequestsIdReject = (
    id: string,
    handlersUpdateDeployApprovalRequestStatusRequest: HandlersUpdateDeployApprovalRequestStatusRequest,
    options?: SecondParameter<
      typeof createGatewayClient<HandlersDeployApprovalRequestResponse>
    >,
  ) => {
    return createGatewayClient<HandlersDeployApprovalRequestResponse>(
      {
        url: `/deploy-approval-requests/${id}/reject`,
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        data: handlersUpdateDeployApprovalRequestStatusRequest,
      },
      options,
    );
  };

  /**
   * Returns service health information.
   * @summary Health check
   */
  const getHealth = (
    options?: SecondParameter<
      typeof createGatewayClient<HandlersHealthResponse>
    >,
  ) => {
    return createGatewayClient<HandlersHealthResponse>(
      { url: `/health`, method: 'GET' },
      options,
    );
  };

  /**
   * Returns user, rack, and integrations status in a single request for app bootstrap
   * @summary Get gateway information
   */
  const getInfo = (
    options?: SecondParameter<typeof createGatewayClient<HandlersInfoResponse>>,
  ) => {
    return createGatewayClient<HandlersInfoResponse>(
      { url: `/info`, method: 'GET' },
      options,
    );
  };

  /**
   * Proxies the rack /system endpoint returning the rack's metadata.
   * @summary Get rack system information
   */
  const getRack = (
    options?: SecondParameter<typeof createGatewayClient<GetRack200>>,
  ) => {
    return createGatewayClient<GetRack200>(
      { url: `/rack`, method: 'GET' },
      options,
    );
  };

  /**
   * Returns metadata and permissions for each gateway RBAC role.
   * @summary List RBAC roles
   */
  const getRoles = (
    options?: SecondParameter<typeof createGatewayClient<GetRoles200>>,
  ) => {
    return createGatewayClient<GetRoles200>(
      { url: `/roles`, method: 'GET' },
      options,
    );
  };

  /**
   * Returns all global settings with their sources (db, env, or default)
   * @summary Get all global settings
   */
  const getSettings = (
    options?: SecondParameter<typeof createGatewayClient<GetSettings200>>,
  ) => {
    return createGatewayClient<GetSettings200>(
      { url: `/settings`, method: 'GET' },
      options,
    );
  };

  /**
   * Updates multiple global settings atomically and stores them in the database
   * @summary Update multiple global settings
   */
  const putSettings = (
    settingsBody: SettingsBody,
    options?: SecondParameter<typeof createGatewayClient<PutSettings200>>,
  ) => {
    return createGatewayClient<PutSettings200>(
      {
        url: `/settings`,
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        data: settingsBody,
      },
      options,
    );
  };

  /**
   * Deletes multiple global settings from the database, reverting to env or default values
   * @summary Delete multiple global settings
   */
  const deleteSettings = (
    params: DeleteSettingsParams,
    options?: SecondParameter<typeof createGatewayClient<DeleteSettings200>>,
  ) => {
    return createGatewayClient<DeleteSettings200>(
      { url: `/settings`, method: 'DELETE', params },
      options,
    );
  };

  /**
   * Fetches and stores the latest TLS certificate for the configured Convox rack.
   * @summary Refresh rack TLS certificate
   */
  const postSettingsRackTlsCertRefresh = (
    options?: SecondParameter<typeof createGatewayClient<DbRackTLSCert>>,
  ) => {
    return createGatewayClient<DbRackTLSCert>(
      { url: `/settings/rack_tls_cert/refresh`, method: 'POST' },
      options,
    );
  };

  /**
   * Returns a single global setting with its source
   * @summary Get a specific global setting
   */
  const getSettingsKey = (
    key: string,
    options?: SecondParameter<typeof createGatewayClient<SettingsSetting>>,
  ) => {
    return createGatewayClient<SettingsSetting>(
      { url: `/settings/${key}`, method: 'GET' },
      options,
    );
  };

  /**
   * Returns every user configured in the gateway along with role assignments.
   * @summary List all gateway users
   */
  const getUsers = (
    options?: SecondParameter<typeof createGatewayClient<DbUser[]>>,
  ) => {
    return createGatewayClient<DbUser[]>(
      { url: `/users`, method: 'GET' },
      options,
    );
  };

  /**
   * Creates a new gateway user with the provided roles.
   * @summary Create a user
   */
  const postUsers = (
    handlersCreateUserRequest: HandlersCreateUserRequest,
    options?: SecondParameter<typeof createGatewayClient<HandlersUserSummary>>,
  ) => {
    return createGatewayClient<HandlersUserSummary>(
      {
        url: `/users`,
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        data: handlersCreateUserRequest,
      },
      options,
    );
  };

  /**
   * Returns details for a single gateway user.
   * @summary Get a user
   */
  const getUsersEmail = (
    email: string,
    options?: SecondParameter<typeof createGatewayClient<DbUser>>,
  ) => {
    return createGatewayClient<DbUser>(
      { url: `/users/${email}`, method: 'GET' },
      options,
    );
  };

  /**
   * Updates a user's email, name, and/or roles in a single request.
   * @summary Update user
   */
  const putUsersEmail = (
    email: string,
    handlersUpdateUserRequest: HandlersUpdateUserRequest,
    options?: SecondParameter<typeof createGatewayClient<HandlersUserSummary>>,
  ) => {
    return createGatewayClient<HandlersUserSummary>(
      {
        url: `/users/${email}`,
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        data: handlersUpdateUserRequest,
      },
      options,
    );
  };

  /**
   * Removes a gateway user and revokes all sessions they own.
   * @summary Delete a user
   */
  const deleteUsersEmail = (
    email: string,
    options?: SecondParameter<typeof createGatewayClient<string>>,
  ) => {
    return createGatewayClient<string>(
      { url: `/users/${email}`, method: 'DELETE' },
      options,
    );
  };

  /**
   * Locks a user account to prevent login
   * @summary Lock a user account
   */
  const postUsersEmailLock = (
    email: string,
    handlersLockUserRequest: HandlersLockUserRequest,
    options?: SecondParameter<
      typeof createGatewayClient<HandlersStatusResponse>
    >,
  ) => {
    return createGatewayClient<HandlersStatusResponse>(
      {
        url: `/users/${email}/lock`,
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        data: handlersLockUserRequest,
      },
      options,
    );
  };

  /**
   * Updates only a user's display name.
   * @summary Update user name
   */
  const putUsersEmailName = (
    email: string,
    handlersUpdateUserNameRequest: HandlersUpdateUserNameRequest,
    options?: SecondParameter<typeof createGatewayClient<HandlersUserSummary>>,
  ) => {
    return createGatewayClient<HandlersUserSummary>(
      {
        url: `/users/${email}/name`,
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        data: handlersUpdateUserNameRequest,
      },
      options,
    );
  };

  /**
   * Returns the active (non-revoked) web sessions for the specified user.
   * @summary List active sessions for a user
   */
  const getUsersEmailSessions = (
    email: string,
    options?: SecondParameter<
      typeof createGatewayClient<HandlersUserSessionResponse[]>
    >,
  ) => {
    return createGatewayClient<HandlersUserSessionResponse[]>(
      { url: `/users/${email}/sessions`, method: 'GET' },
      options,
    );
  };

  /**
   * Revokes every active session belonging to the specified user.
   * @summary Revoke all sessions for a user
   */
  const postUsersEmailSessionsRevokeAll = (
    email: string,
    options?: SecondParameter<
      typeof createGatewayClient<HandlersRevokeAllSessionsResponse>
    >,
  ) => {
    return createGatewayClient<HandlersRevokeAllSessionsResponse>(
      { url: `/users/${email}/sessions/revoke_all`, method: 'POST' },
      options,
    );
  };

  /**
   * Revokes a single session for the specified user.
   * @summary Revoke a user session
   */
  const postUsersEmailSessionsSessionIDRevoke = (
    email: string,
    sessionID: number,
    options?: SecondParameter<
      typeof createGatewayClient<HandlersRevokeSessionResponse>
    >,
  ) => {
    return createGatewayClient<HandlersRevokeSessionResponse>(
      { url: `/users/${email}/sessions/${sessionID}/revoke`, method: 'POST' },
      options,
    );
  };

  /**
   * Unlocks a previously locked user account
   * @summary Unlock a user account
   */
  const postUsersEmailUnlock = (
    email: string,
    options?: SecondParameter<
      typeof createGatewayClient<HandlersStatusResponse>
    >,
  ) => {
    return createGatewayClient<HandlersStatusResponse>(
      { url: `/users/${email}/unlock`, method: 'POST' },
      options,
    );
  };

  return {
    getApiTokens,
    postApiTokens,
    getApiTokensPermissions,
    getApiTokensTokenID,
    putApiTokensTokenID,
    deleteApiTokensTokenID,
    getAppsAppEnv,
    putAppsAppEnv,
    getAppsAppSettings,
    putAppsAppSettings,
    deleteAppsAppSettings,
    putAppsAppSettingsApprovedDeployCommands,
    deleteAppsAppSettingsApprovedDeployCommands,
    putAppsAppSettingsProtectedEnvVars,
    deleteAppsAppSettingsProtectedEnvVars,
    putAppsAppSettingsSecretEnvVars,
    deleteAppsAppSettingsSecretEnvVars,
    putAppsAppSettingsServiceImagePatterns,
    deleteAppsAppSettingsServiceImagePatterns,
    getAuditLogs,
    getAuditLogsExport,
    getAuthCliCallback,
    postAuthCliComplete,
    postAuthCliStart,
    postAuthMfaBackupCodesRegenerate,
    postAuthMfaEnrollTotpConfirm,
    postAuthMfaEnrollTotpStart,
    postAuthMfaEnrollWebauthnConfirm,
    postAuthMfaEnrollWebauthnStart,
    postAuthMfaEnrollYubiotpStart,
    putAuthMfaMethodsMethodID,
    deleteAuthMfaMethodsMethodID,
    putAuthMfaPreferredMethod,
    getAuthMfaStatus,
    postAuthMfaTrustedDevicesTrust,
    deleteAuthMfaTrustedDevicesDeviceID,
    postAuthMfaVerify,
    postAuthMfaWebauthnAssertionStart,
    postAuthMfaWebauthnAssertionVerify,
    getAuthWebCallback,
    getAuthWebLogin,
    getAuthWebLogout,
    getCreatedBy,
    getDeployApprovalRequests,
    postDeployApprovalRequests,
    getDeployApprovalRequestsId,
    postDeployApprovalRequestsIdApprove,
    getDeployApprovalRequestsIdAuditLogs,
    postDeployApprovalRequestsIdReject,
    getHealth,
    getInfo,
    getRack,
    getRoles,
    getSettings,
    putSettings,
    deleteSettings,
    postSettingsRackTlsCertRefresh,
    getSettingsKey,
    getUsers,
    postUsers,
    getUsersEmail,
    putUsersEmail,
    deleteUsersEmail,
    postUsersEmailLock,
    putUsersEmailName,
    getUsersEmailSessions,
    postUsersEmailSessionsRevokeAll,
    postUsersEmailSessionsSessionIDRevoke,
    postUsersEmailUnlock,
  };
};
export type GetApiTokensResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getRackGatewayAPI>['getApiTokens']>>
>;
export type PostApiTokensResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getRackGatewayAPI>['postApiTokens']>>
>;
export type GetApiTokensPermissionsResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getRackGatewayAPI>['getApiTokensPermissions']>
  >
>;
export type GetApiTokensTokenIDResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getRackGatewayAPI>['getApiTokensTokenID']>
  >
>;
export type PutApiTokensTokenIDResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getRackGatewayAPI>['putApiTokensTokenID']>
  >
>;
export type DeleteApiTokensTokenIDResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getRackGatewayAPI>['deleteApiTokensTokenID']>
  >
>;
export type GetAppsAppEnvResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getRackGatewayAPI>['getAppsAppEnv']>>
>;
export type PutAppsAppEnvResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getRackGatewayAPI>['putAppsAppEnv']>>
>;
export type GetAppsAppSettingsResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getRackGatewayAPI>['getAppsAppSettings']>
  >
>;
export type PutAppsAppSettingsResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getRackGatewayAPI>['putAppsAppSettings']>
  >
>;
export type DeleteAppsAppSettingsResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getRackGatewayAPI>['deleteAppsAppSettings']>
  >
>;
export type PutAppsAppSettingsApprovedDeployCommandsResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getRackGatewayAPI
      >['putAppsAppSettingsApprovedDeployCommands']
    >
  >
>;
export type DeleteAppsAppSettingsApprovedDeployCommandsResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getRackGatewayAPI
      >['deleteAppsAppSettingsApprovedDeployCommands']
    >
  >
>;
export type PutAppsAppSettingsProtectedEnvVarsResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getRackGatewayAPI>['putAppsAppSettingsProtectedEnvVars']
    >
  >
>;
export type DeleteAppsAppSettingsProtectedEnvVarsResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getRackGatewayAPI
      >['deleteAppsAppSettingsProtectedEnvVars']
    >
  >
>;
export type PutAppsAppSettingsSecretEnvVarsResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getRackGatewayAPI>['putAppsAppSettingsSecretEnvVars']
    >
  >
>;
export type DeleteAppsAppSettingsSecretEnvVarsResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getRackGatewayAPI>['deleteAppsAppSettingsSecretEnvVars']
    >
  >
>;
export type PutAppsAppSettingsServiceImagePatternsResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getRackGatewayAPI
      >['putAppsAppSettingsServiceImagePatterns']
    >
  >
>;
export type DeleteAppsAppSettingsServiceImagePatternsResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getRackGatewayAPI
      >['deleteAppsAppSettingsServiceImagePatterns']
    >
  >
>;
export type GetAuditLogsResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getRackGatewayAPI>['getAuditLogs']>>
>;
export type GetAuditLogsExportResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getRackGatewayAPI>['getAuditLogsExport']>
  >
>;
export type GetAuthCliCallbackResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getRackGatewayAPI>['getAuthCliCallback']>
  >
>;
export type PostAuthCliCompleteResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getRackGatewayAPI>['postAuthCliComplete']>
  >
>;
export type PostAuthCliStartResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getRackGatewayAPI>['postAuthCliStart']>>
>;
export type PostAuthMfaBackupCodesRegenerateResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getRackGatewayAPI>['postAuthMfaBackupCodesRegenerate']
    >
  >
>;
export type PostAuthMfaEnrollTotpConfirmResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getRackGatewayAPI>['postAuthMfaEnrollTotpConfirm']
    >
  >
>;
export type PostAuthMfaEnrollTotpStartResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getRackGatewayAPI>['postAuthMfaEnrollTotpStart']
    >
  >
>;
export type PostAuthMfaEnrollWebauthnConfirmResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getRackGatewayAPI>['postAuthMfaEnrollWebauthnConfirm']
    >
  >
>;
export type PostAuthMfaEnrollWebauthnStartResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getRackGatewayAPI>['postAuthMfaEnrollWebauthnStart']
    >
  >
>;
export type PostAuthMfaEnrollYubiotpStartResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getRackGatewayAPI>['postAuthMfaEnrollYubiotpStart']
    >
  >
>;
export type PutAuthMfaMethodsMethodIDResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getRackGatewayAPI>['putAuthMfaMethodsMethodID']
    >
  >
>;
export type DeleteAuthMfaMethodsMethodIDResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getRackGatewayAPI>['deleteAuthMfaMethodsMethodID']
    >
  >
>;
export type PutAuthMfaPreferredMethodResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getRackGatewayAPI>['putAuthMfaPreferredMethod']
    >
  >
>;
export type GetAuthMfaStatusResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getRackGatewayAPI>['getAuthMfaStatus']>>
>;
export type PostAuthMfaTrustedDevicesTrustResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getRackGatewayAPI>['postAuthMfaTrustedDevicesTrust']
    >
  >
>;
export type DeleteAuthMfaTrustedDevicesDeviceIDResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getRackGatewayAPI
      >['deleteAuthMfaTrustedDevicesDeviceID']
    >
  >
>;
export type PostAuthMfaVerifyResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getRackGatewayAPI>['postAuthMfaVerify']>>
>;
export type PostAuthMfaWebauthnAssertionStartResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getRackGatewayAPI>['postAuthMfaWebauthnAssertionStart']
    >
  >
>;
export type PostAuthMfaWebauthnAssertionVerifyResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getRackGatewayAPI>['postAuthMfaWebauthnAssertionVerify']
    >
  >
>;
export type GetAuthWebCallbackResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getRackGatewayAPI>['getAuthWebCallback']>
  >
>;
export type GetAuthWebLoginResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getRackGatewayAPI>['getAuthWebLogin']>>
>;
export type GetAuthWebLogoutResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getRackGatewayAPI>['getAuthWebLogout']>>
>;
export type GetCreatedByResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getRackGatewayAPI>['getCreatedBy']>>
>;
export type GetDeployApprovalRequestsResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getRackGatewayAPI>['getDeployApprovalRequests']
    >
  >
>;
export type PostDeployApprovalRequestsResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getRackGatewayAPI>['postDeployApprovalRequests']
    >
  >
>;
export type GetDeployApprovalRequestsIdResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getRackGatewayAPI>['getDeployApprovalRequestsId']
    >
  >
>;
export type PostDeployApprovalRequestsIdApproveResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getRackGatewayAPI
      >['postDeployApprovalRequestsIdApprove']
    >
  >
>;
export type GetDeployApprovalRequestsIdAuditLogsResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getRackGatewayAPI
      >['getDeployApprovalRequestsIdAuditLogs']
    >
  >
>;
export type PostDeployApprovalRequestsIdRejectResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getRackGatewayAPI>['postDeployApprovalRequestsIdReject']
    >
  >
>;
export type GetHealthResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getRackGatewayAPI>['getHealth']>>
>;
export type GetInfoResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getRackGatewayAPI>['getInfo']>>
>;
export type GetRackResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getRackGatewayAPI>['getRack']>>
>;
export type GetRolesResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getRackGatewayAPI>['getRoles']>>
>;
export type GetSettingsResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getRackGatewayAPI>['getSettings']>>
>;
export type PutSettingsResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getRackGatewayAPI>['putSettings']>>
>;
export type DeleteSettingsResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getRackGatewayAPI>['deleteSettings']>>
>;
export type PostSettingsRackTlsCertRefreshResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getRackGatewayAPI>['postSettingsRackTlsCertRefresh']
    >
  >
>;
export type GetSettingsKeyResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getRackGatewayAPI>['getSettingsKey']>>
>;
export type GetUsersResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getRackGatewayAPI>['getUsers']>>
>;
export type PostUsersResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getRackGatewayAPI>['postUsers']>>
>;
export type GetUsersEmailResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getRackGatewayAPI>['getUsersEmail']>>
>;
export type PutUsersEmailResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getRackGatewayAPI>['putUsersEmail']>>
>;
export type DeleteUsersEmailResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getRackGatewayAPI>['deleteUsersEmail']>>
>;
export type PostUsersEmailLockResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getRackGatewayAPI>['postUsersEmailLock']>
  >
>;
export type PutUsersEmailNameResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getRackGatewayAPI>['putUsersEmailName']>>
>;
export type GetUsersEmailSessionsResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getRackGatewayAPI>['getUsersEmailSessions']>
  >
>;
export type PostUsersEmailSessionsRevokeAllResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getRackGatewayAPI>['postUsersEmailSessionsRevokeAll']
    >
  >
>;
export type PostUsersEmailSessionsSessionIDRevokeResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getRackGatewayAPI
      >['postUsersEmailSessionsSessionIDRevoke']
    >
  >
>;
export type PostUsersEmailUnlockResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getRackGatewayAPI>['postUsersEmailUnlock']>
  >
>;
