/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Convox Gateway API
 * API for the Convox Gateway administration and proxy services.
 * OpenAPI spec version: 1.0
 */

export interface DbAPIToken {
  created_at?: string;
  created_by_email?: string;
  created_by_name?: string;
  created_by_user_id?: number;
  expires_at?: string;
  id?: number;
  last_used_at?: string;
  name?: string;
  permissions?: string[];
  user_id?: number;
}
