/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * Rack Gateway API
 * API for the Rack Gateway administration and proxy services.
 * OpenAPI spec version: 1.0
 */

export interface DbAPIToken {
  created_at?: string;
  created_by_email?: string;
  created_by_name?: string;
  created_by_user_id?: number;
  expires_at?: string;
  id?: number;
  last_used_at?: string;
  name?: string;
  permissions?: string[];
  public_id?: string;
  user_id?: number;
}
