/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * Rack Gateway API
 * API for the Rack Gateway administration and proxy services.
 * OpenAPI spec version: 1.0
 */

export interface DbAuditLog {
  /** e.g., "env.read", "user.create", "login.oauth_failed" */
  action?: string;
  /** "convox", "users", "auth" */
  action_type?: string;
  api_token_id?: number;
  api_token_name?: string;
  chain_index?: number;
  checkpoint_hash?: number[];
  checkpoint_id?: string;
  command?: string;
  deploy_approval_request_id?: number;
  /** JSON string */
  details?: string;
  /** Always 1 (aggregation removed) */
  event_count?: number;
  event_hash?: number[];
  http_status?: number;
  id?: number;
  ip_address?: string;
  /** NULL for genesis event */
  previous_hash?: number[];
  /** "allow" or "deny" */
  rbac_decision?: string;
  request_id?: string;
  resource?: string;
  resource_type?: string;
  response_time_ms?: number;
  /** "success", "denied", "error", "blocked" */
  status?: string;
  timestamp?: string;
  user_agent?: string;
  user_email?: string;
  user_name?: string;
}
