/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * Rack Gateway API
 * API for the Rack Gateway administration and proxy services.
 * OpenAPI spec version: 1.0
 */

export interface DbAuditLogAggregated {
  action?: string;
  action_type?: string;
  api_token_id?: number;
  api_token_name?: string;
  avg_response_time_ms?: number;
  command?: string;
  deploy_approval_request_id?: number;
  details?: string;
  event_count?: number;
  first_event_id?: number;
  first_hash?: number[];
  first_seen?: string;
  http_status?: number;
  id?: number;
  ip_address?: string;
  last_event_id?: number;
  last_hash?: number[];
  last_seen?: string;
  max_response_time_ms?: number;
  min_response_time_ms?: number;
  rbac_decision?: string;
  resource?: string;
  resource_type?: string;
  status?: string;
  user_agent?: string;
  user_email?: string;
  user_name?: string;
}
