/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * Rack Gateway API
 * API for the Rack Gateway administration and proxy services.
 * OpenAPI spec version: 1.0
 */

export interface DbCircleCISettings {
  api_token: string;
  approval_job_name: string;
  org_slug?: string;
}
