/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * Rack Gateway API
 * API for the Rack Gateway administration and proxy services.
 * OpenAPI spec version: 1.0
 */

export interface DbRackTLSCert {
  fetched_at?: string;
  fingerprint?: string;
  pem?: string;
}
