/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * Rack Gateway API
 * API for the Rack Gateway administration and proxy services.
 * OpenAPI spec version: 1.0
 */
import type { DbSlackIntegrationChannelActions } from './dbSlackIntegrationChannelActions';

export interface DbSlackIntegration {
  alert_deploy_approvals_channel_id?: string;
  alert_deploy_approvals_enabled?: boolean;
  bot_user_id?: string;
  channel_actions?: DbSlackIntegrationChannelActions;
  created_at?: string;
  created_by_user_id?: number;
  id?: number;
  scope?: string;
  updated_at?: string;
  workspace_id?: string;
  workspace_name?: string;
}
