/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Rack Gateway API
 * API for the Rack Gateway administration and proxy services.
 * OpenAPI spec version: 1.0
 */

export interface DbUser {
  created_at?: string;
  created_by_email?: string;
  created_by_name?: string;
  created_by_user_id?: number;
  email?: string;
  id?: number;
  mfa_enforced_at?: string;
  mfa_enrolled?: boolean;
  name?: string;
  preferred_mfa_method?: string;
  roles?: string[];
  suspended?: boolean;
  updated_at?: string;
}
