/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * Rack Gateway API
 * API for the Rack Gateway administration and proxy services.
 * OpenAPI spec version: 1.0
 */

export type GetAuditLogsParams = {
  /**
   * Text search
   */
  search?: string;
  /**
   * Action type filter
   */
  action_type?: string;
  /**
   * Resource type filter
   */
  resource_type?: string;
  /**
   * Status filter
   */
  status?: string;
  /**
   * Page number
   */
  page?: number;
  /**
   * Page size
   */
  limit?: number;
  /**
   * ISO8601 start time
   */
  start?: string;
  /**
   * ISO8601 end time
   */
  end?: string;
  /**
   * Relative range (e.g. 24h, 7d, custom)
   */
  range?: string;
  /**
   * Filter by user email
   */
  user?: string;
  /**
   * Filter by user ID
   */
  user_id?: string;
};
