/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Rack Gateway API
 * API for the Rack Gateway administration and proxy services.
 * OpenAPI spec version: 1.0
 */

export type GetAuthCliCallbackParams = {
  /**
   * Authorization code
   */
  code?: string;
  /**
   * State
   */
  state: string;
  /**
   * Identity provider error
   */
  error?: string;
};
