/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Convox Gateway API
 * API for the Convox Gateway administration and proxy services.
 * OpenAPI spec version: 1.0
 */

export type GetAdminAuditExportParams = {
  /**
   * Text search
   */
  search?: string;
  /**
   * Action type filter
   */
  action_type?: string;
  /**
   * Resource type filter
   */
  resource_type?: string;
  /**
   * Status filter
   */
  status?: string;
  /**
   * ISO8601 start time
   */
  since?: string;
  /**
   * ISO8601 end time
   */
  until?: string;
};
