/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * Rack Gateway API
 * API for the Rack Gateway administration and proxy services.
 * OpenAPI spec version: 1.0
 */

export type GetAuthWebLoginParams = {
  /**
   * URL to redirect to after successful login (must start with /app/)
   */
  returnTo?: string;
};
