/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Rack Gateway API
 * API for the Rack Gateway administration and proxy services.
 * OpenAPI spec version: 1.0
 */

export type GetAppsAppEnvParams = {
  /**
   * Specific key to fetch
   */
  key?: string;
  /**
   * Include secret values
   */
  secrets?: boolean;
};
