/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Rack Gateway API
 * API for the Rack Gateway administration and proxy services.
 * OpenAPI spec version: 1.0
 */

export type GetAdminDeployApprovalRequestsParams = {
  /**
   * Filter by status
   */
  status?: string;
  /**
   * Only pending/approved
   */
  only_open?: boolean;
  /**
   * Limit
   */
  limit?: number;
  /**
   * Offset
   */
  offset?: number;
};
