/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Rack Gateway API
 * API for the Rack Gateway administration and proxy services.
 * OpenAPI spec version: 1.0
 */

export type GetCreatedByType =
  (typeof GetCreatedByType)[keyof typeof GetCreatedByType];

export const GetCreatedByType = {
  app: "app",
  build: "build",
  release: "release",
} as const;
