/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * Rack Gateway API
 * API for the Rack Gateway administration and proxy services.
 * OpenAPI spec version: 1.0
 */

export type GetDeployApprovalRequestsParams = {
  /**
   * Filter by status (pending, approved, rejected, expired)
   */
  status?: string;
  /**
   * Only return open requests (pending status)
   */
  only_open?: boolean;
  /**
   * Maximum number of results
   */
  limit?: number;
  /**
   * Offset for pagination
   */
  offset?: number;
};
