/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Rack Gateway API
 * API for the Rack Gateway administration and proxy services.
 * OpenAPI spec version: 1.0
 */

export type GetDeployApprovalRequestsIdAuditLogsParams = {
  /**
   * Maximum number of results (default: 100)
   */
  limit?: number;
};
