/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * Rack Gateway API
 * API for the Rack Gateway administration and proxy services.
 * OpenAPI spec version: 1.0
 */

export type GetJobsParams = {
  /**
   * Filter by queue name
   */
  queue?: string;
  /**
   * Filter by job state
   */
  state?: string;
  /**
   * Filter by job kind
   */
  kind?: string;
  /**
   * Maximum number of results (default: 100, max: 1000)
   */
  limit?: number;
};
