/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Rack Gateway API
 * API for the Rack Gateway administration and proxy services.
 * OpenAPI spec version: 1.0
 */
import type { HandlersMFABackupCodesSummary } from './handlersMFABackupCodesSummary';
import type { HandlersMFAMethodResponse } from './handlersMFAMethodResponse';
import type { HandlersTrustedDeviceResponse } from './handlersTrustedDeviceResponse';

export interface HandlersMFAStatusResponse {
  backup_codes: HandlersMFABackupCodesSummary;
  enrolled: boolean;
  methods: HandlersMFAMethodResponse[];
  preferred_method?: string;
  recent_step_up_expires_at?: string;
  required: boolean;
  trusted_devices: HandlersTrustedDeviceResponse[];
  webauthn_available: boolean;
}
