/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * Rack Gateway API
 * API for the Rack Gateway administration and proxy services.
 * OpenAPI spec version: 1.0
 */

export interface HandlersConfirmTOTPEnrollmentRequest {
  code: string;
  label?: string;
  method_id: number;
  trust_device?: boolean;
}
