/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Rack Gateway API
 * API for the Rack Gateway administration and proxy services.
 * OpenAPI spec version: 1.0
 */

export interface HandlersUserSessionResponse {
  channel: string;
  created_at: string;
  expires_at: string;
  id: number;
  ip_address?: string;
  last_seen_at: string;
  metadata?: unknown;
  user_agent?: string;
}
