/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * Rack Gateway API
 * API for the Rack Gateway administration and proxy services.
 * OpenAPI spec version: 1.0
 */
import type { HandlersIntegrationsInfo } from './handlersIntegrationsInfo';
import type { HandlersRackSummary } from './handlersRackSummary';
import type { HandlersUserInfo } from './handlersUserInfo';

export interface HandlersInfoResponse {
  integrations: HandlersIntegrationsInfo;
  rack: HandlersRackSummary;
  user: HandlersUserInfo;
}
