/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Rack Gateway API
 * API for the Rack Gateway administration and proxy services.
 * OpenAPI spec version: 1.0
 */

export interface HandlersVerifyWebAuthnAssertionRequest {
  assertion_response: string;
  session_data: string;
  trust_device?: boolean;
}
