/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * Rack Gateway API
 * API for the Rack Gateway administration and proxy services.
 * OpenAPI spec version: 1.0
 */

export interface HandlersMFAMethodResponse {
  confirmed_at?: string;
  created_at: string;
  id: number;
  label?: string;
  last_used_at?: string;
  type: string;
}
