/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Rack Gateway API
 * API for the Rack Gateway administration and proxy services.
 * OpenAPI spec version: 1.0
 */

export interface HandlersCLILoginResponse {
  channel?: string;
  device_id?: string;
  device_name?: string;
  email?: string;
  enrollment_required?: boolean;
  expires_at?: string;
  mfa_required?: boolean;
  mfa_verified?: boolean;
  name?: string;
  session_id?: number;
  token?: string;
}
