/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Rack Gateway API
 * API for the Rack Gateway administration and proxy services.
 * OpenAPI spec version: 1.0
 */

export interface HandlersUpdateMFAMethodRequest {
  /** Optional: only for WebAuthn methods */
  cli_capable?: boolean;
  /** @maxLength 150 */
  label: string;
}
