/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * Rack Gateway API
 * API for the Rack Gateway administration and proxy services.
 * OpenAPI spec version: 1.0
 */

export interface HandlersCreateAPITokenRequest {
  name: string;
  /** Explicit permissions (overrides role) */
  permissions?: string[];
  /** Role shortcut (viewer, ops, deployer, cicd, admin) */
  role?: string;
  user_email?: string;
}
