/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * Rack Gateway API
 * API for the Rack Gateway administration and proxy services.
 * OpenAPI spec version: 1.0
 */
import type { HandlersRackSummary } from './handlersRackSummary';

export interface HandlersCurrentUserResponse {
  deploy_approvals_enabled: boolean;
  email: string;
  has_trusted_device: boolean;
  mfa_enrolled: boolean;
  mfa_required: boolean;
  name: string;
  permissions: string[];
  preferred_mfa_method?: string;
  rack?: HandlersRackSummary;
  recent_step_up_expires_at?: string;
  roles: string[];
}
