/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Convox Gateway API
 * API for the Convox Gateway administration and proxy services.
 * OpenAPI spec version: 1.0
 */
import type { HandlersRoleDescriptor } from './handlersRoleDescriptor';

export interface HandlersTokenPermissionMetadata {
  default_permissions?: string[];
  permissions?: string[];
  roles?: HandlersRoleDescriptor[];
  user_permissions?: string[];
  user_roles?: string[];
}
