/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * Rack Gateway API
 * API for the Rack Gateway administration and proxy services.
 * OpenAPI spec version: 1.0
 */

export interface HandlersUserInfo {
  email: string;
  has_trusted_device: boolean;
  mfa_enrolled: boolean;
  mfa_required: boolean;
  name: string;
  preferred_mfa_method?: string;
  recent_step_up_expires_at?: string;
  roles: string[];
}
