/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Rack Gateway API
 * API for the Rack Gateway administration and proxy services.
 * OpenAPI spec version: 1.0
 */

export interface HandlersVerifyWebAuthnAssertionRequest {
  assertion_response: string;
  /** SessionData is the challenge ID returned by /auth/mfa/webauthn/assertion/start. */
  session_data: string;
  trust_device?: boolean;
}
