/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Rack Gateway API
 * API for the Rack Gateway administration and proxy services.
 * OpenAPI spec version: 1.0
 */

export interface HandlersCLILoginCompleteRequest {
  client_version?: string;
  code_verifier: string;
  device_id?: string;
  device_name?: string;
  device_os?: string;
  state: string;
}
