/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Convox Gateway API
 * API for the Convox Gateway administration and proxy services.
 * OpenAPI spec version: 1.0
 */

export interface HandlersMFABackupCodesSummary {
  last_generated_at?: string;
  last_used_at?: string;
  total?: number;
  unused?: number;
}
