/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Rack Gateway API
 * API for the Rack Gateway administration and proxy services.
 * OpenAPI spec version: 1.0
 */
import type { HandlersUpdateEnvValuesRequestSet } from "./handlersUpdateEnvValuesRequestSet";

export interface HandlersUpdateEnvValuesRequest {
  remove?: string[];
  set?: HandlersUpdateEnvValuesRequestSet;
}
