/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Rack Gateway API
 * API for the Rack Gateway administration and proxy services.
 * OpenAPI spec version: 1.0
 */

export interface HandlersWebAuthnAssertionStartResponse {
  /** protocol.CredentialAssertion */
  options?: unknown;
  /** Serialized session to send back with verification */
  session_data?: string;
}
