/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * Rack Gateway API
 * API for the Rack Gateway administration and proxy services.
 * OpenAPI spec version: 1.0
 */
import type { HandlersJobErrorResponse } from './handlersJobErrorResponse';

export interface HandlersJobResponse {
  args?: number[];
  attempt?: number;
  attempted_at?: string;
  created_at?: string;
  errors?: HandlersJobErrorResponse[];
  finalized_at?: string;
  id?: number;
  kind?: string;
  last_error?: string;
  max_attempts?: number;
  queue?: string;
  scheduled_at?: string;
  state?: string;
}
