/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Rack Gateway API
 * API for the Rack Gateway administration and proxy services.
 * OpenAPI spec version: 1.0
 */

export interface HandlersCreateAPITokenRequest {
  /** Optional expiry; the token stops working after this time */
  expires_at?: string;
  name: string;
  /** Explicit permissions (overrides role) */
  permissions?: string[];
  /** Role shortcut (viewer, ops, deployer, cicd, admin) */
  role?: string;
  user_email?: string;
}
