/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * Rack Gateway API
 * API for the Rack Gateway administration and proxy services.
 * OpenAPI spec version: 1.0
 */

export interface HandlersMFABackupCodesSummary {
  last_generated_at?: string;
  last_used_at?: string;
  total?: number;
  unused?: number;
}
