/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Rack Gateway API
 * API for the Rack Gateway administration and proxy services.
 * OpenAPI spec version: 1.0
 */

export interface HandlersWebAuthnAssertionStartResponse {
  /** protocol.CredentialAssertion */
  options: unknown;
  /**
   * SessionData is an opaque, single-use challenge ID to send back with the assertion.
   * The challenge itself is stored server-side and expires after a few minutes.
   */
  session_data: string;
}
