/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Convox Gateway API
 * API for the Convox Gateway administration and proxy services.
 * OpenAPI spec version: 1.0
 */
import type { HandlersMFABackupCodesSummary } from './handlersMFABackupCodesSummary';
import type { HandlersMFAMethodResponse } from './handlersMFAMethodResponse';
import type { HandlersTrustedDeviceResponse } from './handlersTrustedDeviceResponse';

export interface HandlersMFAStatusResponse {
  backup_codes?: HandlersMFABackupCodesSummary;
  enrolled?: boolean;
  methods?: HandlersMFAMethodResponse[];
  recent_step_up_expires_at?: string;
  required?: boolean;
  trusted_devices?: HandlersTrustedDeviceResponse[];
  webauthn_available?: boolean;
}
