/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Rack Gateway API
 * API for the Rack Gateway administration and proxy services.
 * OpenAPI spec version: 1.0
 */
import type { HandlersCreateDeployApprovalRequestRequestCiMetadata } from './handlersCreateDeployApprovalRequestRequestCiMetadata';

export interface HandlersCreateDeployApprovalRequestRequest {
  app: string;
  ci_metadata?: HandlersCreateDeployApprovalRequestRequestCiMetadata;
  git_branch?: string;
  git_commit_hash: string;
  message: string;
  target_api_token?: string;
  target_api_token_id?: string;
}
