/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * Rack Gateway API
 * API for the Rack Gateway administration and proxy services.
 * OpenAPI spec version: 1.0
 */
import type { HandlersRoleDescriptor } from './handlersRoleDescriptor';

export interface HandlersTokenPermissionMetadata {
  default_permissions: string[];
  permissions: string[];
  roles: HandlersRoleDescriptor[];
  user_permissions: string[];
  user_roles: string[];
}
