/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Convox Gateway API
 * API for the Convox Gateway administration and proxy services.
 * OpenAPI spec version: 1.0
 */

export interface HandlersMFAMethodResponse {
  confirmed_at?: string;
  created_at?: string;
  id?: number;
  label?: string;
  last_used_at?: string;
  type?: string;
}
