/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * Rack Gateway API
 * API for the Rack Gateway administration and proxy services.
 * OpenAPI spec version: 1.0
 */

export interface HandlersCLILoginStartRequest {
  code_challenge: string;
  code_challenge_method: string;
  device_name?: string;
  redirect_uri: string;
  state: string;
}
