/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Convox Gateway API
 * API for the Convox Gateway administration and proxy services.
 * OpenAPI spec version: 1.0
 */

export interface HandlersVerifyMFAResponse {
  mfa_verified_at?: string;
  recent_step_up_expires_at?: string;
  trusted_device_cookie?: boolean;
}
