/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * Rack Gateway API
 * API for the Rack Gateway administration and proxy services.
 * OpenAPI spec version: 1.0
 */
import type { DbAPIToken } from './dbAPIToken';

export interface HandlersCreateAPITokenResponse {
  api_token: DbAPIToken;
  id: number;
  name: string;
  permissions: string[];
  token: string;
}
