/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * Rack Gateway API
 * API for the Rack Gateway administration and proxy services.
 * OpenAPI spec version: 1.0
 */

export interface HandlersTrustedDeviceResponse {
  created_at: string;
  expires_at: string;
  id: number;
  ip_address?: string;
  label: string;
  last_used_at?: string;
  revoked_at?: string;
  revoked_reason?: string;
  user_agent?: string;
}
