/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * Rack Gateway API
 * API for the Rack Gateway administration and proxy services.
 * OpenAPI spec version: 1.0
 */

export interface HandlersVerifyMFAResponse {
  mfa_verified_at: string;
  recent_step_up_expires_at: string;
  trusted_device_cookie: boolean;
}
