/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * Rack Gateway API
 * API for the Rack Gateway administration and proxy services.
 * OpenAPI spec version: 1.0
 */
import type { DbAuditLogAggregated } from './dbAuditLogAggregated';

export interface HandlersAuditLogsResponse {
  limit: number;
  logs: DbAuditLogAggregated[];
  page: number;
  total: number;
}
