/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * Rack Gateway API
 * API for the Rack Gateway administration and proxy services.
 * OpenAPI spec version: 1.0
 */
import type { HandlersDeployApprovalRequestResponse } from './handlersDeployApprovalRequestResponse';

export interface HandlersDeployApprovalRequestList {
  deploy_approval_requests: HandlersDeployApprovalRequestResponse[];
}
