/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * Rack Gateway API
 * API for the Rack Gateway administration and proxy services.
 * OpenAPI spec version: 1.0
 */

export interface HandlersCreateUserRequest {
  email: string;
  name: string;
  /** @minItems 1 */
  roles: string[];
}
