/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Convox Gateway API
 * API for the Convox Gateway administration and proxy services.
 * OpenAPI spec version: 1.0
 */
import type { HandlersDeployRequestResponse } from './handlersDeployRequestResponse';

export interface HandlersDeployRequestList {
  deploy_requests?: HandlersDeployRequestResponse[];
}
