/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Convox Gateway API
 * API for the Convox Gateway administration and proxy services.
 * OpenAPI spec version: 1.0
 */
import type { DbAuditLog } from './dbAuditLog';

export interface HandlersAuditLogsResponse {
  limit?: number;
  logs?: DbAuditLog[];
  page?: number;
  total?: number;
}
