/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Convox Gateway API
 * API for the Convox Gateway administration and proxy services.
 * OpenAPI spec version: 1.0
 */

export interface HandlersConfirmTOTPEnrollmentRequest {
  code: string;
  method_id: number;
  trust_device?: boolean;
}
