/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * Rack Gateway API
 * API for the Rack Gateway administration and proxy services.
 * OpenAPI spec version: 1.0
 */
import type { HandlersJobResponse } from './handlersJobResponse';

export interface HandlersJobListResponse {
  /** Number of jobs in this response (not total count across all pages) */
  count?: number;
  jobs?: HandlersJobResponse[];
  limit?: number;
}
