/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Convox Gateway API
 * API for the Convox Gateway administration and proxy services.
 * OpenAPI spec version: 1.0
 */

export interface HandlersUserSessionResponse {
  created_at?: string;
  expires_at?: string;
  id?: number;
  ip_address?: string;
  last_seen_at?: string;
  metadata?: unknown;
  user_agent?: string;
}
