/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * Rack Gateway API
 * API for the Rack Gateway administration and proxy services.
 * OpenAPI spec version: 1.0
 */
import type { HandlersJobResponse } from './handlersJobResponse';
import type { PaginationPageInfo } from './paginationPageInfo';

export interface HandlersJobListResponse {
  jobs?: HandlersJobResponse[];
  page_info?: PaginationPageInfo;
}
