/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Convox Gateway API
 * API for the Convox Gateway administration and proxy services.
 * OpenAPI spec version: 1.0
 */
import type { DbAPIToken } from './dbAPIToken';

export interface HandlersCreateAPITokenResponse {
  api_token?: DbAPIToken;
  id?: number;
  name?: string;
  permissions?: string[];
  token?: string;
}
