/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * Rack Gateway API
 * API for the Rack Gateway administration and proxy services.
 * OpenAPI spec version: 1.0
 */

export interface HandlersStartTOTPEnrollmentResponse {
  backup_codes?: string[];
  method_id?: number;
  secret?: string;
  uri?: string;
}
