/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Convox Gateway API
 * API for the Convox Gateway administration and proxy services.
 * OpenAPI spec version: 1.0
 */

export interface HandlersCreateDeployRequestRequest {
  message: string;
  rack?: string;
  target_api_token?: string;
  target_api_token_id?: number;
}
