/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Convox Gateway API
 * API for the Convox Gateway administration and proxy services.
 * OpenAPI spec version: 1.0
 */

export interface HandlersDeployRequestResponse {
  approval_expires_at?: string;
  approval_notes?: string;
  approved_at?: string;
  approved_by_email?: string;
  approved_by_name?: string;
  build_created_at?: string;
  build_id?: string;
  created_at?: string;
  created_by_email?: string;
  created_by_name?: string;
  id?: number;
  message?: string;
  object_created_at?: string;
  object_key?: string;
  rack?: string;
  rejected_at?: string;
  rejected_by_email?: string;
  rejected_by_name?: string;
  release_created_at?: string;
  release_id?: string;
  release_promoted_at?: string;
  release_promoted_by_api_token_id?: number;
  status?: string;
  target_api_token_id?: number;
  target_api_token_name?: string;
  updated_at?: string;
}
