/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * Rack Gateway API
 * API for the Rack Gateway administration and proxy services.
 * OpenAPI spec version: 1.0
 */

export interface PaginationPageInfo {
  end_cursor?: string;
  has_next_page?: boolean;
  has_previous_page?: boolean;
  start_cursor?: string;
  /** Optional - omit for expensive counts (River) */
  total_count?: number;
}
