/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * Rack Gateway API
 * API for the Rack Gateway administration and proxy services.
 * OpenAPI spec version: 1.0
 */
import type { SettingsSettingSource } from './settingsSettingSource';

export interface SettingsSetting {
  /** e.g., "RGW_SETTING_REQUIRE_MFA_ALL_USERS" */
  env_var?: string;
  source?: SettingsSettingSource;
  value?: unknown;
}
