/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Rack Gateway API
 * API for the Rack Gateway administration and proxy services.
 * OpenAPI spec version: 1.0
 */

export type SettingsSettingSource =
  (typeof SettingsSettingSource)[keyof typeof SettingsSettingSource];

export const SettingsSettingSource = {
  SourceDB: "db",
  SourceEnv: "env",
  SourceDefault: "default",
  SourceGlobalDefault: "global_default",
} as const;
