package dbtest

import (
	"crypto/rand"
	"database/sql"
	"encoding/binary"
	"fmt"
	"net/url"
	"os"
	"strings"
	"testing"
	"time"

	"github.com/DocSpring/rack-gateway/internal/gateway/db"
)

// NewDatabase creates a unique temporary Postgres database for a test, copied from a fully migrated
// template (see template.go), and returns a connected *db.Database. The database is dropped on test cleanup.
// Sets TEST_DATABASE_URL env var to the created database DSN for subprocesses.
func NewDatabase(t *testing.T) *db.Database {
	t.Helper()
	baseDSN := getBaseDSN()
	admin, adminCleanup := setupAdminConnection(t, baseDSN)

	dbName := generateTestDBName()
	cloneTemplate(t, admin, dbName, ensureTemplate(t, admin, baseDSN))

	dsn := buildTestDSN(t, baseDSN, dbName)
	waitForDatabaseReady(t, dsn)

	app := connectAppDatabase(t, dsn)
	registerCleanup(t, app, admin, adminCleanup, dbName)

	return app
}

func getBaseDSN() string {
	base := os.Getenv("TEST_DATABASE_URL")
	if base != "" {
		return base
	}

	// Build from PG* env
	host := getenv("PGHOST", "localhost")
	port := getenv("PGPORT", "5432")
	user := getenv("PGUSER", getenv("USER", "postgres"))
	dbname := getenv("PGDATABASE", user)
	ssl := getenv("PGSSLMODE", "disable")
	return fmt.Sprintf("postgres://%s@%s:%s/%s?sslmode=%s", user, host, port, dbname, ssl)
}

func setupAdminConnection(t *testing.T, baseDSN string) (*sql.DB, func()) {
	t.Helper()
	u, err := url.Parse(baseDSN)
	if err != nil {
		t.Fatalf("invalid TEST_DATABASE_URL: %v", err)
	}
	u.Path = "/postgres"
	admin, err := sql.Open("pgx", u.String())
	if err != nil {
		t.Fatalf("open admin: %v", err)
	}
	// Limit admin connection pool to avoid exhaustion during parallel tests
	admin.SetMaxOpenConns(2)
	admin.SetMaxIdleConns(1)
	admin.SetConnMaxLifetime(5 * time.Minute)

	return admin, func() {
		if err := admin.Close(); err != nil {
			t.Fatalf("close admin connection: %v", err)
		}
	}
}

func generateTestDBName() string {
	var b [8]byte
	if _, err := rand.Read(b[:]); err != nil {
		panic(fmt.Sprintf("failed to generate random bytes: %v", err))
	}
	// Mask to ensure we stay within int64 positive range (0 to MaxInt64)
	// G115: Masked to prevent overflow
	randomNum := int64(binary.LittleEndian.Uint64(b[:]) & 0x7FFFFFFFFFFFFFFF) //nolint:gosec
	return fmt.Sprintf("rgw_test_%d_%d", time.Now().UnixNano(), randomNum)
}

func buildTestDSN(t *testing.T, baseDSN, dbName string) string {
	t.Helper()
	u, err := url.Parse(baseDSN)
	if err != nil {
		t.Fatalf("invalid base DSN: %v", err)
	}
	u.Path = "/" + dbName
	return u.String()
}

func waitForDatabaseReady(t *testing.T, dsn string) {
	t.Helper()
	for i := 0; i < 300; i++ {
		testConn, err := sql.Open("pgx", dsn)
		if err == nil {
			if err = testConn.Ping(); err == nil {
				if cerr := testConn.Close(); cerr != nil {
					t.Fatalf("close test connection: %v", cerr)
				}
				return
			}
			if cerr := testConn.Close(); cerr != nil {
				t.Fatalf("close test connection: %v", cerr)
			}
		}
		time.Sleep(50 * time.Millisecond)
	}
	t.Fatal("database did not become ready in time")
}

func connectAppDatabase(t *testing.T, dsn string) *db.Database {
	t.Helper()

	// The database is a copy of the migrated template, so there's nothing to migrate.
	app, err := db.NewWithPoolConfigAndMigration(dsn, nil, false)
	if err != nil {
		t.Fatalf("open app db: %v", err)
	}
	// Set TEST_DATABASE_URL for subprocesses
	os.Setenv("TEST_DATABASE_URL", dsn) //nolint:errcheck,gosec // G104: ignore error
	return app
}

func createAuditRoles(t *testing.T, sqlDB *sql.DB) {
	t.Helper()

	// Create the three audit roles (IF NOT EXISTS for idempotency)
	// These match the roles created by setup-audit-roles.sh
	_, err := sqlDB.Exec(`
		DO $$
		BEGIN
			IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'audit_owner') THEN
				CREATE ROLE audit_owner NOLOGIN;
			END IF;
			IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'audit_writer') THEN
				CREATE ROLE audit_writer NOLOGIN;
			END IF;
			IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'audit_reader') THEN
				CREATE ROLE audit_reader NOLOGIN;
			END IF;
		END
		$$;

		-- Grant audit_owner to postgres user (equivalent to rack_gateway_admin in production)
		GRANT audit_owner TO postgres;
	`)
	if err != nil {
		t.Fatalf("create audit roles: %v", err)
	}
}

func registerCleanup(t *testing.T, app *db.Database, admin *sql.DB, adminCleanup func(), dbName string) {
	t.Helper()
	t.Cleanup(func() {
		if err := app.Close(); err != nil {
			t.Fatalf("close app database: %v", err)
		}

		// Terminate all connections to the database before dropping
		// This prevents DROP DATABASE from hanging on active connections
		//nolint:gosec // G201: dbName is generated by code and properly quoted with pqQuoteLiteral
		terminateSQL := fmt.Sprintf(`
			SELECT pg_terminate_backend(pg_stat_activity.pid)
			FROM pg_stat_activity
			WHERE pg_stat_activity.datname = %s
			AND pid <> pg_backend_pid()`,
			pqQuoteLiteral(dbName))
		if _, err := admin.Exec(terminateSQL); err != nil {
			// Don't fail on this - database might not exist or have no connections
			t.Logf("Warning: failed to terminate connections: %v", err)
		}

		if _, err := admin.Exec("DROP DATABASE IF EXISTS " + pqQuoteIdent(dbName)); err != nil {
			t.Fatalf("drop database %s: %v", dbName, err)
		}
		// Close admin connection after dropping the test database
		adminCleanup()
	})
}

func getenv(k, def string) string {
	if v := os.Getenv(k); v != "" {
		return v
	}
	return def
}

// simple identifier quoting
func pqQuoteIdent(s string) string { return `"` + strings.ReplaceAll(s, `"`, `""`) + `"` }

// simple string literal quoting
func pqQuoteLiteral(s string) string { return `'` + strings.ReplaceAll(s, `'`, `''`) + `'` }

// split out for testability; replace with time.Now().UnixNano()
// no-op
