// Re-export autogenerated Slack integration type from OpenAPI spec
export type { DbSlackIntegration as SlackIntegration } from '@/api/schemas/dbSlackIntegration'

// Frontend-only types for Slack integration UI
export type SlackChannel = {
  id: string
  name: string
}

export type ChannelConfig = {
  id: string | null
  name: string
  actions: string[]
}
