// Code generated by "stringer -type=Action -linecomment"; DO NOT EDIT.

package rbac

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ActionAdd-0]
	_ = x[ActionApprove-1]
	_ = x[ActionCreate-2]
	_ = x[ActionDelete-3]
	_ = x[ActionDeployWithApproval-4]
	_ = x[ActionExec-5]
	_ = x[ActionGenerate-6]
	_ = x[ActionImport-7]
	_ = x[ActionKeyroll-8]
	_ = x[ActionList-9]
	_ = x[ActionManage-10]
	_ = x[ActionPromote-11]
	_ = x[ActionRead-12]
	_ = x[ActionRemove-13]
	_ = x[ActionRestart-14]
	_ = x[ActionSet-15]
	_ = x[ActionStart-16]
	_ = x[ActionStop-17]
	_ = x[ActionTerminate-18]
	_ = x[ActionUnset-19]
	_ = x[ActionUpdate-20]
	_ = x[ActionUpdateName-21]
}

const _Action_name = "addapprovecreatedeletedeploy_with_approvalexecgenerateimportkeyrolllistmanagepromotereadremoverestartsetstartstopterminateunsetupdateupdate_name"

var _Action_index = [...]uint8{0, 3, 10, 16, 22, 42, 46, 54, 60, 67, 71, 77, 84, 88, 94, 101, 104, 109, 113, 122, 127, 133, 144}

func (i Action) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Action_index)-1 {
		return "Action(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Action_name[_Action_index[idx]:_Action_index[idx+1]]
}
