// Code generated by "stringer -type=Resource -linecomment"; DO NOT EDIT.

package rbac

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ResourceApp-0]
	_ = x[ResourceBuild-1]
	_ = x[ResourceCert-2]
	_ = x[ResourceDeploy-3]
	_ = x[ResourceEnv-4]
	_ = x[ResourceInstance-5]
	_ = x[ResourceLog-6]
	_ = x[ResourceObject-7]
	_ = x[ResourceProcess-8]
	_ = x[ResourceRack-9]
	_ = x[ResourceRegistry-10]
	_ = x[ResourceRelease-11]
	_ = x[ResourceResource-12]
	_ = x[ResourceAPIToken-13]
	_ = x[ResourceDeployApprovalRequest-14]
	_ = x[ResourceIntegration-15]
	_ = x[ResourceSecret-16]
	_ = x[ResourceSetting-17]
	_ = x[ResourceUser-18]
	_ = x[ResourceAuth-19]
	_ = x[ResourceMFABackupCodes-20]
	_ = x[ResourceMFAMethod-21]
	_ = x[ResourceMFAPreferences-22]
	_ = x[ResourceMFAVerification-23]
	_ = x[ResourceTrustedDevice-24]
}

const _Resource_name = "appbuildcertdeployenvinstancelogobjectprocessrackregistryreleaseresourceapi_tokendeploy_approval_requestintegrationsecretsettinguserauthmfa_backup_codesmfa_methodmfa_preferencesmfa_verificationtrusted_device"

var _Resource_index = [...]uint8{0, 3, 8, 12, 18, 21, 29, 32, 38, 45, 49, 57, 64, 72, 81, 104, 115, 121, 128, 132, 136, 152, 162, 177, 193, 207}

func (i Resource) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Resource_index)-1 {
		return "Resource(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Resource_name[_Resource_index[idx]:_Resource_index[idx+1]]
}
