// Code generated by "stringer -type=Scope -linecomment"; DO NOT EDIT.

package rbac

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ScopeAuth-0]
	_ = x[ScopeConvox-1]
	_ = x[ScopeGateway-2]
	_ = x[ScopeSecurity-3]
}

const _Scope_name = "authconvoxgatewaysecurity"

var _Scope_index = [...]uint8{0, 4, 10, 17, 25}

func (i Scope) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Scope_index)-1 {
		return "Scope(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Scope_name[_Scope_index[idx]:_Scope_index[idx+1]]
}
